#include "pyc/Dialect/PYC/PYCDialect.h"
#include "pyc/Dialect/PYC/PYCOps.h"
#include "pyc/Emit/CppEmitter.h"
#include "pyc/Emit/VerilogEmitter.h"
#include "pyc/Transforms/Passes.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/Extensions/InlinerExtension.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/PassInstrumentation.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"

#include "cpp/pyc_probe_registry.hpp"

#include <algorithm>
#include <chrono>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cstdint>
#include <fstream>
#include <limits>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include <sys/resource.h>

#if defined(__APPLE__)
#include <mach/mach.h>
#elif defined(__linux__)
#include <unistd.h>
#endif

using namespace mlir;

static void addRemoveDeadValuesPassIfSupported(PassManager &pm) {
#if LLVM_VERSION_MAJOR >= 19
  // LLVM 19's RemoveDeadValues currently crashes on some generated pyc module
  // shapes while erasing function arguments. The rest of the pipeline already
  // runs SymbolDCE/CSE/SCCP/canonicalization and our legality passes, so keep
  // the flow stable by skipping this cleanup pass on LLVM 19+.
  (void)pm;
#else
  pm.addPass(createRemoveDeadValuesPass());
#endif
}

static llvm::cl::opt<std::string> inputFilename(llvm::cl::Positional, llvm::cl::desc("<input .pyc>"),
                                                llvm::cl::init("-"));

static llvm::cl::opt<std::string> outputFilename("o", llvm::cl::desc("Output file"), llvm::cl::init("-"));

static llvm::cl::opt<std::string> emitKind("emit", llvm::cl::desc("Emission target: verilog|cpp|none"),
                                           llvm::cl::init("verilog"));

static llvm::cl::opt<std::string> directCppOut(
    "cpp",
    llvm::cl::desc("Direct C++ output path (equivalent to --emit=cpp -o <path>)"),
    llvm::cl::init(""));

static llvm::cl::opt<std::string> directVerilogOut(
    "verilog",
    llvm::cl::desc("Direct Verilog output path (equivalent to --emit=verilog -o <path>)"),
    llvm::cl::init(""));

static llvm::cl::opt<std::string> cppSplitMode(
    "cpp-split",
    llvm::cl::desc("C++ out-dir split mode: module|none"),
    llvm::cl::init("module"));

static llvm::cl::opt<unsigned> cppShardThresholdLines(
    "cpp-shard-threshold-lines",
    llvm::cl::desc("Shard oversized C++ module sources when generated line count exceeds this threshold"),
    llvm::cl::init(120000));

static llvm::cl::opt<unsigned> cppShardThresholdBytes(
    "cpp-shard-threshold-bytes",
    llvm::cl::desc("Shard oversized C++ module sources when generated byte count exceeds this threshold"),
    llvm::cl::init(4 * 1024 * 1024));

static llvm::cl::opt<unsigned> cppShardMaxAstNodes(
    "cpp-shard-max-ast-nodes",
    llvm::cl::desc("Chunk large eval topologies into helper methods (node budget per chunk; 0=default policy)"),
    llvm::cl::init(0));

static llvm::cl::opt<std::string> cppManifestPath(
    "cpp-manifest",
    llvm::cl::desc("C++ compile manifest path (default: <out-dir>/cpp_compile_manifest.json)"),
    llvm::cl::init(""));

static llvm::cl::opt<std::string> probeManifestPath(
    "probe-manifest",
    llvm::cl::desc("Write DFX probe manifest JSON to this path (Decision 0100)"),
    llvm::cl::init(""));

static llvm::cl::opt<std::string> probePlanPath(
    "probe-plan",
    llvm::cl::desc("Resolved @probe alias plan JSON to embed into generated ProbeRegistry registration"),
    llvm::cl::init(""));

static llvm::cl::opt<std::string> targetKind("target", llvm::cl::desc("Target: default|fpga"),
                                             llvm::cl::init("default"));

static llvm::cl::opt<bool> includePrims("include-primitives",
                                        llvm::cl::desc("Emit `include` for PYC Verilog primitives"),
                                        llvm::cl::init(true));

static llvm::cl::opt<std::string>
    outDir("out-dir", llvm::cl::desc("Output directory (split per module; emits manifest.json)"), llvm::cl::init(""));

static llvm::cl::opt<unsigned> logicDepthLimit(
    "logic-depth",
    llvm::cl::desc("Maximum combinational logic depth allowed between sequential boundaries"),
    llvm::cl::init(32));

static llvm::cl::opt<std::string> simMode("sim-mode", llvm::cl::desc("Simulation mode: default|cpp-only"),
                                          llvm::cl::init("default"));

static llvm::cl::opt<bool> cppOnlyPreserveOps(
    "cpp-only-preserve-ops",
    llvm::cl::desc("Preserve operation-granular C++ scheduling in --sim-mode=cpp-only (disables comb fusion)"),
    llvm::cl::init(false));

static llvm::cl::opt<bool> noInline(
    "noinline",
    llvm::cl::desc("Disable MLIR inliner to preserve module boundaries (prevents merge/flatten)"),
    llvm::cl::init(false));

static llvm::cl::opt<std::string> buildProfile(
    "build-profile",
    llvm::cl::desc("Build profile: release|dev-fast"),
    llvm::cl::init("release"));

static llvm::cl::opt<std::string> inlinePolicy(
    "inline-policy",
    llvm::cl::desc("Inliner policy: default|off|threshold:<op-count>"),
    llvm::cl::init("default"));

static llvm::cl::opt<std::string> hierarchyPolicy(
    "hierarchy-policy",
    llvm::cl::desc("Module hierarchy policy: strict"),
    llvm::cl::init("strict"));

static llvm::cl::opt<unsigned> canonicalizeBudget(
    "canonicalize-budget",
    llvm::cl::desc("Canonicalizer budget (max iterations; 0 keeps profile default)"),
    llvm::cl::init(0));

static llvm::cl::opt<std::string> profileJsonPath(
    "profile-json",
    llvm::cl::desc("Write compile profile JSON report to this path"),
    llvm::cl::init(""));

static llvm::cl::opt<bool> profilePassTiming(
    "profile-pass-timing",
    llvm::cl::desc("Collect pass-level timing and memory stats (included in --profile-json)"),
    llvm::cl::init(false));

static llvm::cl::opt<std::string> emitStructuralMode(
    "emit-structural",
    llvm::cl::desc("Structural emission policy for comb fusion: auto|on|off"),
    llvm::cl::init("auto"));

static std::string topSymbol(ModuleOp module) {
  if (auto topAttr = module->getAttrOfType<FlatSymbolRefAttr>("pyc.top"))
    return topAttr.getValue().str();
  if (auto first = module.getOps<func::FuncOp>().begin(); first != module.getOps<func::FuncOp>().end())
    return (*first).getSymName().str();
  return "";
}

static std::set<std::string> collectFrontendModuleSymbols(ModuleOp module) {
  std::set<std::string> out;
  for (func::FuncOp f : module.getOps<func::FuncOp>()) {
    auto kind = f->getAttrOfType<StringAttr>("pyc.kind");
    if (!kind || kind.getValue() != "module")
      continue;
    out.insert(f.getSymName().str());
  }
  return out;
}

static LogicalResult writeFile(llvm::StringRef path, llvm::StringRef contents) {
  std::error_code ec;
  llvm::raw_fd_ostream os(path, ec, llvm::sys::fs::OF_Text);
  if (ec) {
    llvm::errs() << "error: cannot open " << path << ": " << ec.message() << "\n";
    return failure();
  }
  os << contents;
  return success();
}

// Decision 0021: hash64 algorithm is xxHash64 (seed=0 by default).
static std::uint64_t xxhash64(llvm::StringRef data, std::uint64_t seed = 0) {
  constexpr std::uint64_t PRIME1 = 11400714785074694791ULL;
  constexpr std::uint64_t PRIME2 = 14029467366897019727ULL;
  constexpr std::uint64_t PRIME3 = 1609587929392839161ULL;
  constexpr std::uint64_t PRIME4 = 9650029242287828579ULL;
  constexpr std::uint64_t PRIME5 = 2870177450012600261ULL;

  auto rotl = [](std::uint64_t x, int r) -> std::uint64_t { return (x << r) | (x >> (64 - r)); };

  auto read64 = [](const std::uint8_t *p) -> std::uint64_t {
    std::uint64_t v = 0;
    std::memcpy(&v, p, sizeof(v));
#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
    v = __builtin_bswap64(v);
#endif
    return v;
  };

  auto read32 = [](const std::uint8_t *p) -> std::uint32_t {
    std::uint32_t v = 0;
    std::memcpy(&v, p, sizeof(v));
#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
    v = __builtin_bswap32(v);
#endif
    return v;
  };

  auto round = [&](std::uint64_t acc, std::uint64_t input) -> std::uint64_t {
    acc += input * PRIME2;
    acc = rotl(acc, 31);
    acc *= PRIME1;
    return acc;
  };

  auto mergeRound = [&](std::uint64_t acc, std::uint64_t val) -> std::uint64_t {
    val = round(0, val);
    acc ^= val;
    acc = acc * PRIME1 + PRIME4;
    return acc;
  };

  const std::uint8_t *p = reinterpret_cast<const std::uint8_t *>(data.data());
  const std::uint8_t *end = p + data.size();

  std::uint64_t h64 = 0;
  if (data.size() >= 32) {
    std::uint64_t v1 = seed + PRIME1 + PRIME2;
    std::uint64_t v2 = seed + PRIME2;
    std::uint64_t v3 = seed + 0;
    std::uint64_t v4 = seed - PRIME1;

    const std::uint8_t *limit = end - 32;
    do {
      v1 = round(v1, read64(p));
      p += 8;
      v2 = round(v2, read64(p));
      p += 8;
      v3 = round(v3, read64(p));
      p += 8;
      v4 = round(v4, read64(p));
      p += 8;
    } while (p <= limit);

    h64 = rotl(v1, 1) + rotl(v2, 7) + rotl(v3, 12) + rotl(v4, 18);
    h64 = mergeRound(h64, v1);
    h64 = mergeRound(h64, v2);
    h64 = mergeRound(h64, v3);
    h64 = mergeRound(h64, v4);
  } else {
    h64 = seed + PRIME5;
  }

  h64 += static_cast<std::uint64_t>(data.size());

  while (p + 8 <= end) {
    std::uint64_t k1 = read64(p);
    k1 *= PRIME2;
    k1 = rotl(k1, 31);
    k1 *= PRIME1;
    h64 ^= k1;
    h64 = rotl(h64, 27) * PRIME1 + PRIME4;
    p += 8;
  }

  if (p + 4 <= end) {
    h64 ^= static_cast<std::uint64_t>(read32(p)) * PRIME1;
    h64 = rotl(h64, 23) * PRIME2 + PRIME3;
    p += 4;
  }

  while (p < end) {
    h64 ^= static_cast<std::uint64_t>(*p) * PRIME5;
    h64 = rotl(h64, 11) * PRIME1;
    ++p;
  }

  // Avalanche.
  h64 ^= h64 >> 33;
  h64 *= PRIME2;
  h64 ^= h64 >> 29;
  h64 *= PRIME3;
  h64 ^= h64 >> 32;
  return h64;
}

static std::uint64_t hash64ForPath(llvm::StringRef path) {
  // Decision 0021: seed=0 default.
  return xxhash64(path, /*seed=*/0);
}

static std::uint64_t hash64ForPathWithSuffix(llvm::StringRef path, std::uint32_t suffix) {
  std::string tmp;
  tmp.reserve(path.size() + 1 + 10);
  tmp.append(path.data(), path.size());
  tmp.push_back('#');
  tmp.append(std::to_string(static_cast<unsigned>(suffix)));
  return hash64ForPath(tmp);
}

static std::string u64Hex(std::uint64_t v) {
  char buf[32];
  std::snprintf(buf, sizeof(buf), "0x%016llx", static_cast<unsigned long long>(v));
  return std::string(buf);
}

static std::string typeToString(Type ty) {
  std::string out;
  llvm::raw_string_ostream os(out);
  ty.print(os);
  os.flush();
  return out;
}

static unsigned bitWidth(Type ty) {
  if (isa<pyc::ClockType>(ty) || isa<pyc::ResetType>(ty))
    return 1;
  auto intTy = dyn_cast<IntegerType>(ty);
  return intTy ? intTy.getWidth() : 0;
}

static std::string getPortCanonicalFieldPath(func::FuncOp f, unsigned idx, bool isResult) {
  if (!isResult) {
    if (auto names = f->getAttrOfType<ArrayAttr>("arg_names")) {
      if (idx < names.size())
        if (auto s = dyn_cast<StringAttr>(names[idx]))
          return s.getValue().str();
    }
    return "arg" + std::to_string(idx);
  }
  if (auto names = f->getAttrOfType<ArrayAttr>("result_names")) {
    if (idx < names.size())
      if (auto s = dyn_cast<StringAttr>(names[idx]))
        return s.getValue().str();
  }
  return "out" + std::to_string(idx);
}

struct ProbeManifestEntry {
  std::string canonical_path{};
  std::string instance_path{};
  std::string field_path{};
  std::string module{};
  std::string kind{};
  std::string subkind{};
  std::string dir{};
  std::uint32_t width_bits = 0;
  std::string ty{};
  std::uint64_t probe_id = 0;
  std::optional<std::string> obs{};
  llvm::json::Value tags = nullptr;
};

struct ProbeManifestInstance {
  std::string module{};
  std::string instance_path{};
};

struct ProbeManifestIndex {
  llvm::StringMap<std::size_t> by_path{};
  llvm::DenseMap<std::uint64_t, std::size_t> by_id{};
};

static std::uint64_t assignProbeId(llvm::StringRef path, const ProbeManifestIndex &idx) {
  // Decision 0022: detect collisions and resolve by rehashing with "#<n>" suffix.
  const std::uint64_t base = hash64ForPath(path);
  std::uint64_t id = base;
  if (idx.by_id.count(id)) {
    std::uint32_t suffix = 1;
    do {
      id = hash64ForPathWithSuffix(path, suffix);
      ++suffix;
    } while (idx.by_id.count(id));
    llvm::errs() << "[pyc] Probe manifest hash collision: base=" << u64Hex(base) << " path='" << path
                 << "' resolved=" << u64Hex(id) << "\n";
  }
  return id;
}

static LogicalResult writeProbeManifestJson(llvm::StringRef path,
                                           llvm::StringRef top,
                                           llvm::StringRef rootInstance,
                                           llvm::ArrayRef<ProbeManifestInstance> instances,
                                           llvm::ArrayRef<ProbeManifestEntry> entries) {
  llvm::json::Object root;
  root["version"] = 3;
  root["top"] = top.str();
  root["root_instance"] = rootInstance.str();
  root["probe_id_alg"] = "xxhash64(seed=0)";
  root["instance_path_alg"] = "short_name+xxhash64(mid-elide,v1)";
  {
    pyc::cpp::InstancePathShorteningPolicy pol{};
    llvm::json::Object obj;
    obj["max_segments"] = static_cast<int64_t>(pol.max_segments);
    obj["max_chars"] = static_cast<int64_t>(pol.max_chars);
    obj["keep_head"] = static_cast<int64_t>(pol.keep_head);
    obj["keep_tail"] = static_cast<int64_t>(pol.keep_tail);
    root["instance_path_policy"] = std::move(obj);
  }
  root["probe_count"] = static_cast<int64_t>(entries.size());

  llvm::json::Array instJson;
  instJson.reserve(instances.size());
  for (const auto &inst : instances) {
    llvm::json::Object obj;
    obj["module"] = inst.module;
    obj["instance_path"] = inst.instance_path;
    instJson.push_back(std::move(obj));
  }
  root["instances"] = std::move(instJson);

  llvm::json::Array probes;
  llvm::json::Array entriesJson;
  probes.reserve(entries.size());
  entriesJson.reserve(entries.size());
  for (const auto &e : entries) {
    llvm::json::Object obj;
    obj["canonical_path"] = e.canonical_path;
    obj["probe_id"] = u64Hex(e.probe_id);
    obj["kind"] = e.kind;
    obj["subkind"] = e.subkind;
    obj["dir"] = e.dir;
    obj["width_bits"] = static_cast<int64_t>(e.width_bits);
    obj["ty"] = e.ty;
    obj["module"] = e.module;
    obj["instance_path"] = e.instance_path;
    obj["field_path"] = e.field_path;
    if (e.obs.has_value())
      obj["obs"] = *e.obs;
    if (e.tags.kind() != llvm::json::Value::Null)
      obj["tags"] = e.tags;
    probes.push_back(std::move(obj));
    llvm::json::Object obj2;
    obj2["canonical_path"] = e.canonical_path;
    obj2["probe_id"] = u64Hex(e.probe_id);
    obj2["kind"] = e.kind;
    obj2["subkind"] = e.subkind;
    obj2["dir"] = e.dir;
    obj2["width_bits"] = static_cast<int64_t>(e.width_bits);
    obj2["ty"] = e.ty;
    obj2["module"] = e.module;
    obj2["instance_path"] = e.instance_path;
    obj2["field_path"] = e.field_path;
    if (e.obs.has_value())
      obj2["obs"] = *e.obs;
    if (e.tags.kind() != llvm::json::Value::Null)
      obj2["tags"] = e.tags;
    entriesJson.push_back(std::move(obj2));
  }
  root["probes"] = std::move(probes);
  root["entries"] = std::move(entriesJson);

  std::string buf;
  llvm::raw_string_ostream ss(buf);
  llvm::json::OStream j(ss, 2);
  llvm::json::Value v(std::move(root));
  j.value(v);
  ss << "\n";
  ss.flush();
  return writeFile(path, buf);
}

static LogicalResult emitProbeManifest(ModuleOp module, llvm::StringRef outPath) {
  std::string top = topSymbol(module);
  if (top.empty()) {
    module.emitError("[PYC970] cannot emit probe manifest: missing `pyc.top`");
    return failure();
  }

  auto topFunc = module.lookupSymbol<func::FuncOp>(top);
  if (!topFunc) {
    module.emitError("[PYC971] cannot emit probe manifest: top symbol not found: ") << top;
    return failure();
  }

  ProbeManifestIndex idx;
  std::vector<ProbeManifestEntry> entries;
  entries.reserve(1024);
  std::vector<ProbeManifestInstance> instances;
  instances.reserve(128);
  llvm::StringSet<> instanceSeen;

  llvm::SmallVector<std::string> stack;
  stack.reserve(16);

  auto addEntry = [&](ProbeManifestEntry e) -> LogicalResult {
    if (e.canonical_path.empty())
      return success();
    if (idx.by_path.count(e.canonical_path))
      return success();
    e.probe_id = assignProbeId(e.canonical_path, idx);
    const std::size_t slot = entries.size();
    idx.by_path.try_emplace(e.canonical_path, slot);
    idx.by_id.try_emplace(e.probe_id, slot);
    entries.push_back(std::move(e));
    return success();
  };

  auto rec = [&](auto &&self, func::FuncOp f, std::string instPath) -> LogicalResult {
    const std::string sym = f.getSymName().str();
    if (std::find(stack.begin(), stack.end(), sym) != stack.end()) {
      f.emitError() << "[PYC972] recursive instance hierarchy is not supported for probe manifest: " << sym;
      return failure();
    }
    stack.push_back(sym);

    const std::string canonInstPath = pyc::cpp::shortenInstancePath(instPath);
    if (instanceSeen.insert(canonInstPath).second)
      instances.push_back(ProbeManifestInstance{sym, canonInstPath});

    struct HardenedProbeMeta {
      std::string at{};
      llvm::json::Value tags = nullptr;
    };
    llvm::StringMap<HardenedProbeMeta> probeMetaByPort;
    if (auto hardenedAttr = f->getAttrOfType<StringAttr>("pyc.hardened")) {
      llvm::Expected<llvm::json::Value> parsed = llvm::json::parse(hardenedAttr.getValue());
      if (parsed) {
        if (auto *obj = parsed->getAsObject()) {
          if (auto *probeTable = obj->getObject("probe_table")) {
            for (const auto &kv : *probeTable) {
              auto metaObj = kv.second.getAsObject();
              if (!metaObj)
                continue;
              HardenedProbeMeta meta;
              if (auto at = metaObj->getString("at"))
                meta.at = at->str();
              if (auto *tags = metaObj->getObject("tags"))
                meta.tags = llvm::json::Object(*tags);
              probeMetaByPort.try_emplace(llvm::StringRef(kv.first), std::move(meta));
            }
          }
        }
      }
    }

    // Decision 0003 / 0051-0052: infer which module results directly expose a
    // local state element (pyc.reg q). For declarations we conservatively treat
    // all results as combinational.
    std::vector<bool> outIsReg(f.getNumResults(), false);
    if (!f.isDeclaration()) {
      auto ret = dyn_cast_or_null<func::ReturnOp>(f.getBody().front().getTerminator());
      if (!ret) {
        f.emitError("[PYC975] probe manifest emission requires func.return terminator");
        return failure();
      }
      auto isRegQ = [&](Value v) -> bool {
        llvm::SmallVector<Value, 8> seen;
        while (true) {
          for (Value prev : seen) {
            if (prev == v)
              return false;
          }
          seen.push_back(v);
          while (auto a = v.getDefiningOp<pyc::AliasOp>())
            v = a.getIn();
          if (v.getDefiningOp<pyc::RegOp>() != nullptr)
            return true;
          auto comb = v.getDefiningOp<pyc::CombOp>();
          if (!comb)
            return false;

          auto res = dyn_cast<OpResult>(v);
          if (!res)
            return false;
          auto yield = dyn_cast_or_null<pyc::YieldOp>(comb.getBody().front().getTerminator());
          if (!yield)
            return false;
          if (res.getResultNumber() >= yield.getNumOperands())
            return false;

          Value y = yield.getOperand(res.getResultNumber());
          while (auto a = y.getDefiningOp<pyc::AliasOp>())
            y = a.getIn();
          auto barg = dyn_cast<BlockArgument>(y);
          if (!barg)
            return false;
          if (barg.getOwner() != &comb.getBody().front())
            return false;
          if (barg.getArgNumber() >= comb.getNumOperands())
            return false;
          v = comb.getOperand(barg.getArgNumber());
        }
      };
      for (unsigned i = 0; i < f.getNumResults() && i < ret.getNumOperands(); ++i)
        outIsReg[i] = isRegQ(ret.getOperand(i));
    }

    for (auto [i, arg] : llvm::enumerate(f.getArguments())) {
      ProbeManifestEntry e;
      e.instance_path = canonInstPath;
      e.field_path = getPortCanonicalFieldPath(f, i, /*isResult=*/false);
      e.canonical_path = canonInstPath + ":" + e.field_path;
      e.module = sym;
      e.kind = "comb";
      e.subkind = "wire";
      e.dir = "in";
      e.width_bits = bitWidth(arg.getType());
      e.ty = typeToString(arg.getType());
      if (failed(addEntry(std::move(e))))
        return failure();
    }

    for (unsigned i = 0; i < f.getNumResults(); ++i) {
      ProbeManifestEntry e;
      e.instance_path = canonInstPath;
      e.field_path = getPortCanonicalFieldPath(f, i, /*isResult=*/true);
      e.canonical_path = canonInstPath + ":" + e.field_path;
      e.module = sym;
      e.kind = outIsReg[i] ? "state" : "comb";
      e.subkind = outIsReg[i] ? "reg" : "wire";
      e.dir = "out";
      e.width_bits = bitWidth(f.getResultTypes()[i]);
      e.ty = typeToString(f.getResultTypes()[i]);
      if (auto it = probeMetaByPort.find(e.field_path); it != probeMetaByPort.end()) {
        const auto &meta = it->second;
        if (!meta.at.empty())
          e.obs = meta.at;
        if (meta.tags.kind() != llvm::json::Value::Null)
          e.tags = meta.tags;
      }
      if (failed(addEntry(std::move(e))))
        return failure();
    }

    if (f.isDeclaration()) {
      stack.pop_back();
      return success();
    }

    auto findRegQ = [&](Value v) -> Value {
      llvm::SmallVector<Value, 8> seen;
      while (true) {
        for (Value prev : seen) {
          if (prev == v)
            return Value();
        }
        seen.push_back(v);
        while (auto a = v.getDefiningOp<pyc::AliasOp>())
          v = a.getIn();
        if (auto rop = v.getDefiningOp<pyc::RegOp>())
          return rop.getQ();
        auto comb = v.getDefiningOp<pyc::CombOp>();
        if (!comb)
          return Value();

        auto res = dyn_cast<OpResult>(v);
        if (!res)
          return Value();
        auto yield = dyn_cast_or_null<pyc::YieldOp>(comb.getBody().front().getTerminator());
        if (!yield)
          return Value();
        if (res.getResultNumber() >= yield.getNumOperands())
          return Value();

        Value y = yield.getOperand(res.getResultNumber());
        while (auto a = y.getDefiningOp<pyc::AliasOp>())
          y = a.getIn();
        auto barg = dyn_cast<BlockArgument>(y);
        if (!barg)
          return Value();
        if (barg.getOwner() != &comb.getBody().front())
          return Value();
        if (barg.getArgNumber() >= comb.getNumOperands())
          return Value();
        v = comb.getOperand(barg.getArgNumber());
      }
    };

    if (!llvm::hasSingleElement(f.getBody()))
      return f.emitError("[PYC973] probe manifest emission requires single-block funcs (match C++ emitter contract)");

    Block &topBlock = f.getBody().front();

    llvm::StringSet<> localNamedFields;
    f.walk([&](Operation *op) {
      auto nameAttr = op->getAttrOfType<StringAttr>("pyc.name");
      if (!nameAttr)
        return;
      if (op->getNumResults() != 1)
        return;
      Value value = op->getResult(0);
      const unsigned width = bitWidth(value.getType());
      if (width == 0)
        return;
      const std::string fieldPath = nameAttr.getValue().str();
      if (!localNamedFields.insert(fieldPath).second)
        return;

      ProbeManifestEntry e;
      e.instance_path = canonInstPath;
      e.field_path = fieldPath;
      e.canonical_path = canonInstPath + ":" + e.field_path;
      e.module = sym;
      const bool isReg = static_cast<bool>(findRegQ(value));
      e.kind = isReg ? "state" : "comb";
      e.subkind = isReg ? "reg" : "wire";
      e.dir = "internal";
      e.width_bits = width;
      e.ty = typeToString(value.getType());
      (void)addEntry(std::move(e));
    });

    auto collectMemNames = [&](auto pred) -> std::vector<std::string> {
      std::vector<std::string> out;
      for (Operation &op : topBlock) {
        if (!pred(op))
          continue;
        if (auto nameAttr = op.getAttrOfType<StringAttr>("name"))
          out.push_back(nameAttr.getValue().str());
      }
      std::sort(out.begin(), out.end());
      out.erase(std::unique(out.begin(), out.end()), out.end());
      return out;
    };

    // Decision 0006: mem probes exist and must have stable names (enforced by frontend contract pass).
    const auto byteMems = collectMemNames([](Operation &op) { return isa<pyc::ByteMemOp>(op); });
    for (const auto &name : byteMems) {
      ProbeManifestEntry e;
      e.instance_path = canonInstPath;
      e.field_path = name;
      e.canonical_path = canonInstPath + ":" + name;
      e.module = sym;
      e.kind = "state";
      e.subkind = "mem";
      e.dir = "mem";
      e.width_bits = 0;
      e.ty = "mem";
      if (failed(addEntry(std::move(e))))
        return failure();
    }

    const auto syncMems = collectMemNames([](Operation &op) { return isa<pyc::SyncMemOp>(op); });
    for (const auto &name : syncMems) {
      ProbeManifestEntry e;
      e.instance_path = canonInstPath;
      e.field_path = name;
      e.canonical_path = canonInstPath + ":" + name;
      e.module = sym;
      e.kind = "state";
      e.subkind = "mem";
      e.dir = "mem";
      e.width_bits = 0;
      e.ty = "mem";
      if (failed(addEntry(std::move(e))))
        return failure();
    }

    const auto syncMemDPs = collectMemNames([](Operation &op) { return isa<pyc::SyncMemDPOp>(op); });
    for (const auto &name : syncMemDPs) {
      ProbeManifestEntry e;
      e.instance_path = canonInstPath;
      e.field_path = name;
      e.canonical_path = canonInstPath + ":" + name;
      e.module = sym;
      e.kind = "state";
      e.subkind = "mem";
      e.dir = "mem";
      e.width_bits = 0;
      e.ty = "mem";
      if (failed(addEntry(std::move(e))))
        return failure();
    }

    struct ChildInfo {
      std::string name;
      std::string seg;
      func::FuncOp callee;
    };
    std::vector<ChildInfo> children;
    for (Operation &op : topBlock) {
      auto inst = dyn_cast<pyc::InstanceOp>(op);
      if (!inst)
        continue;
      auto nameAttr = inst.getNameAttr();
      if (!nameAttr)
        return inst.emitError("[PYC974] missing required InstanceOp name (expected frontend contract to enforce)");
      auto calleeAttr = inst.getCalleeAttr();
      if (!calleeAttr)
        return inst.emitError("missing required FlatSymbolRefAttr `callee`");
      auto callee = module.lookupSymbol<func::FuncOp>(calleeAttr.getValue());
      if (!callee)
        return inst.emitError("callee symbol not found: ") << calleeAttr.getValue();
      std::string seg = nameAttr.getValue().str();
      if (auto shortAttr = inst->getAttrOfType<StringAttr>("short_name"))
        seg = shortAttr.getValue().str();
      children.push_back(ChildInfo{std::string(nameAttr.getValue()), std::move(seg), callee});
    }
    std::sort(children.begin(), children.end(), [](const ChildInfo &a, const ChildInfo &b) { return a.name < b.name; });

    for (const auto &c : children) {
      std::string childPath = instPath;
      childPath.push_back('.');
      childPath.append(c.seg);
      if (failed(self(self, c.callee, std::move(childPath))))
        return failure();
    }

    stack.pop_back();
    return success();
  };

  if (failed(rec(rec, topFunc, "dut")))
    return failure();

  std::sort(entries.begin(), entries.end(), [](const ProbeManifestEntry &a, const ProbeManifestEntry &b) {
    return a.canonical_path < b.canonical_path;
  });

  return writeProbeManifestJson(outPath, top, "dut", instances, entries);
}

static std::optional<std::string> getTbPayloadAttr(ModuleOp module) {
  if (auto a = module->getAttrOfType<StringAttr>("pyc.tb.payload"))
    return a.getValue().str();
  return std::nullopt;
}

static FailureOr<llvm::json::Object> parseTbPayload(ModuleOp module) {
  auto payloadOpt = getTbPayloadAttr(module);
  if (!payloadOpt)
    return failure();
  auto parsed = llvm::json::parse(*payloadOpt);
  if (!parsed || !parsed->getAsObject()) {
    module.emitError("[PYC920] invalid `pyc.tb.payload` JSON encoding");
    return failure();
  }
  return *parsed->getAsObject();
}

static LogicalResult emitTbTextFromPayload(ModuleOp module, llvm::StringRef kind, llvm::raw_ostream &os) {
  auto payloadOr = parseTbPayload(module);
  if (failed(payloadOr))
    return failure();
  auto payload = *payloadOr;
  if (kind == "cpp") {
    if (auto txt = payload.getString("cpp_text")) {
      os << txt->str();
      return success();
    }
    module.emitError("[PYC921] testbench payload missing `cpp_text`");
    return failure();
  }
  if (kind == "verilog") {
    if (auto txt = payload.getString("sv_text")) {
      os << txt->str();
      return success();
    }
    module.emitError("[PYC922] testbench payload missing `sv_text`");
    return failure();
  }
  module.emitError("[PYC923] unsupported testbench emit kind `") << kind << "`";
  return failure();
}

static std::optional<std::string> findPrimitivesDir(const char *argv0) {
  // Allow explicit override (useful for installed toolchains).
  if (const char *env = std::getenv("PYC_PRIMITIVES_DIR")) {
    llvm::SmallString<256> cand(env);
    llvm::sys::path::append(cand, "pyc_reg.v");
    if (llvm::sys::fs::exists(cand))
      return std::string(env);
  }

  auto tryDir = [&](llvm::SmallString<256> dir) -> std::optional<std::string> {
    llvm::SmallString<256> probe(dir);
    llvm::sys::path::append(probe, "pyc_reg.v");
    if (llvm::sys::fs::exists(probe))
      return dir.str().str();
    return std::nullopt;
  };

  auto tryRoot = [&](llvm::StringRef root) -> std::optional<std::string> {
    llvm::SmallString<256> dir(root);
    llvm::sys::path::append(dir, "runtime", "verilog");
    if (auto d = tryDir(dir))
      return d;

    dir = root;
    llvm::sys::path::append(dir, "include", "verilog");
    if (auto d = tryDir(dir))
      return d;

    dir = root;
    llvm::sys::path::append(dir, "include", "pyc", "verilog");
    if (auto d = tryDir(dir))
      return d;
    return std::nullopt;
  };

  // Current working directory.
  llvm::SmallString<256> cwd;
  if (!llvm::sys::fs::current_path(cwd)) {
    if (auto d = tryRoot(cwd))
      return d;
  }

  // Walk up from the executable path (common for in-tree builds).
  llvm::SmallString<256> exe(argv0 ? argv0 : "");
  if (!exe.empty()) {
    llvm::SmallString<256> rp;
    if (!llvm::sys::fs::real_path(exe, rp)) {
      llvm::SmallString<256> cur = llvm::sys::path::parent_path(rp);
      for (unsigned i = 0; i < 6 && !cur.empty(); ++i) {
        if (auto d = tryRoot(cur))
          return d;
        cur = llvm::sys::path::parent_path(cur);
      }
    }
  }

  return std::nullopt;
}

static const char *runtimeLibBasename() {
#if defined(_WIN32)
  return "pyc4_runtime.lib";
#else
  return "libpyc4_runtime.a";
#endif
}

static std::optional<std::string> findToolchainRoot(const char *argv0) {
  auto tryRoot = [&](llvm::SmallString<256> root) -> std::optional<std::string> {
    llvm::SmallString<256> runtimeLib(root);
    llvm::sys::path::append(runtimeLib, "lib", runtimeLibBasename());
    llvm::SmallString<256> cmakeCfg(root);
    llvm::sys::path::append(cmakeCfg, "share", "pycircuit", "cmake", "pycircuitConfig.cmake");
    if (llvm::sys::fs::exists(runtimeLib) || llvm::sys::fs::exists(cmakeCfg))
      return root.str().str();
    return std::nullopt;
  };

  if (const char *env = std::getenv("PYC_TOOLCHAIN_ROOT")) {
    llvm::SmallString<256> root(env);
    if (auto found = tryRoot(root))
      return found;
  }

  llvm::ErrorOr<std::string> resolved = llvm::sys::findProgramByName(argv0 ? argv0 : "");
  llvm::SmallString<256> exePath;
  if (resolved) {
    exePath = *resolved;
  } else if (argv0 && *argv0) {
    exePath = argv0;
  }
  if (exePath.empty())
    return std::nullopt;

  llvm::SmallString<256> realExe;
  if (llvm::sys::fs::real_path(exePath, realExe))
    realExe = exePath;
  llvm::SmallString<256> parent = llvm::sys::path::parent_path(realExe);
  if (llvm::sys::path::filename(parent) == "bin") {
    llvm::SmallString<256> root = llvm::sys::path::parent_path(parent);
    if (auto found = tryRoot(root))
      return found;
  }

  llvm::SmallString<256> cur = parent;
  for (unsigned i = 0; i < 6 && !cur.empty(); ++i) {
    if (auto found = tryRoot(cur))
      return found;
    cur = llvm::sys::path::parent_path(cur);
  }
  return std::nullopt;
}

static LogicalResult emitPrimitivesFile(llvm::StringRef outPath, llvm::StringRef primDir, bool targetFpga) {
  static const char *kFiles[] = {
      "pyc_reg.v",
      "pyc_fifo.v",
      "pyc_byte_mem.v",
      "pyc_sync_mem.v",
      "pyc_sync_mem_dp.v",
      "pyc_async_fifo.v",
      "pyc_cdc_sync.v",
  };

  std::string buf;
  llvm::raw_string_ostream ss(buf);
  ss << "// pyCircuit Verilog primitives (concatenated)\n";
  ss << "/* verilator lint_off DECLFILENAME */\n\n";
  if (targetFpga)
    ss << "`define PYC_TARGET_FPGA 1\n\n";
  for (const char *name : kFiles) {
    llvm::SmallString<256> path(primDir);
    llvm::sys::path::append(path, name);
    auto fileOrErr = llvm::MemoryBuffer::getFile(path);
    if (!fileOrErr) {
      llvm::errs() << "error: cannot read primitive file: " << path << "\n";
      return failure();
    }
    ss << "// --- " << name << "\n";
    ss << fileOrErr->get()->getBuffer() << "\n\n";
  }
  ss << "/* verilator lint_on DECLFILENAME */\n";
  ss.flush();
  return writeFile(outPath, buf);
}

static LogicalResult updateManifest(llvm::StringRef outDirPath, llvm::StringRef top,
                                   std::optional<llvm::json::Array> verilogMods,
                                   std::optional<llvm::json::Array> cppMods) {
  llvm::SmallString<256> path(outDirPath);
  llvm::sys::path::append(path, "manifest.json");

  llvm::json::Object manifest;
  if (llvm::sys::fs::exists(path)) {
    if (auto mb = llvm::MemoryBuffer::getFile(path)) {
      if (auto parsed = llvm::json::parse(mb->get()->getBuffer())) {
        if (auto *obj = parsed->getAsObject())
          manifest = *obj;
      }
    }
  }

  manifest["top"] = top.str();
  if (!manifest.get("verilog_modules"))
    manifest["verilog_modules"] = llvm::json::Array();
  if (!manifest.get("cpp_modules"))
    manifest["cpp_modules"] = llvm::json::Array();
  if (verilogMods)
    manifest["verilog_modules"] = std::move(*verilogMods);
  if (cppMods)
    manifest["cpp_modules"] = std::move(*cppMods);

  std::string buf;
  llvm::raw_string_ostream ss(buf);
  llvm::json::OStream j(ss, 2);
  llvm::json::Value v(std::move(manifest));
  j.value(v);
  ss << "\n";
  ss.flush();
  return writeFile(path, buf);
}

struct CppManifestSource {
  std::string path;
  std::string module;
  std::string shard;
  std::string kind;
  bool probeOnly = false;
  uint64_t bytes = 0;
  uint64_t lines = 0;
  uint64_t complexityScore = 0;
  double predictedCompileCost = 0.0;
  std::string sourceHash;
};

static bool isProbeOnlyFunc(func::FuncOp f) {
  if (auto attr = f->getAttrOfType<BoolAttr>("pyc.probe_only"))
    return attr.getValue();
  return false;
}

static constexpr double kHardMaxSourcePredictedCompileCost = 50000.0;
static constexpr double kHardMaxModulePredictedCompileCost = 40000.0;
static constexpr double kHardMaxTotalPredictedCompileCost = 700000.0;

static LogicalResult enforceCppCompileBudgets(ModuleOp module, llvm::ArrayRef<CppManifestSource> sources) {
  double totalCost = 0.0;
  double topSourceCost = 0.0;
  llvm::StringRef topSourcePath;
  llvm::StringMap<double> moduleCosts;

  for (const auto &src : sources) {
    if (src.probeOnly)
      continue;
    totalCost += src.predictedCompileCost;
    if (src.predictedCompileCost > topSourceCost) {
      topSourceCost = src.predictedCompileCost;
      topSourcePath = src.path;
    }
    moduleCosts[src.module] += src.predictedCompileCost;
  }

  llvm::StringRef topModuleName;
  double topModuleCost = 0.0;
  for (const auto &it : moduleCosts) {
    if (it.getValue() > topModuleCost) {
      topModuleCost = it.getValue();
      topModuleName = it.getKey();
    }
  }

  bool ok = true;
  if (topSourceCost > kHardMaxSourcePredictedCompileCost) {
    module.emitError() << "[PYC991] hottest emitted C++ TU exceeds hard budget: path=`" << topSourcePath
                       << "` predicted_compile_cost=" << topSourceCost
                       << " > " << kHardMaxSourcePredictedCompileCost;
    ok = false;
  }
  if (topModuleCost > kHardMaxModulePredictedCompileCost) {
    module.emitError() << "[PYC992] hottest emitted module exceeds hard budget: module=`" << topModuleName
                       << "` predicted_compile_cost=" << topModuleCost
                       << " > " << kHardMaxModulePredictedCompileCost;
    ok = false;
  }
  if (totalCost > kHardMaxTotalPredictedCompileCost) {
    module.emitError() << "[PYC993] total emitted C++ compile cost exceeds hard budget: predicted_compile_cost="
                       << totalCost << " > " << kHardMaxTotalPredictedCompileCost;
    ok = false;
  }
  return ok ? success() : failure();
}

struct SplitMethodDef {
  std::string name;
  std::string declaration;
  std::string definition;
  std::string kind;
  size_t bytes = 0;
  size_t lines = 0;
};

struct SplitModuleResult {
  std::string headerBody;
  std::vector<SplitMethodDef> methods;
};

static std::string trimCopy(llvm::StringRef s) {
  size_t b = 0;
  size_t e = s.size();
  while (b < e && std::isspace(static_cast<unsigned char>(s[b])))
    ++b;
  while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1])))
    --e;
  return s.substr(b, e - b).str();
}

static std::string normalizeWhitespace(llvm::StringRef s) {
  std::string out;
  out.reserve(s.size());
  bool prevSpace = false;
  for (char c : s) {
    if (std::isspace(static_cast<unsigned char>(c))) {
      if (!prevSpace) {
        out.push_back(' ');
        prevSpace = true;
      }
    } else {
      out.push_back(c);
      prevSpace = false;
    }
  }
  return trimCopy(out);
}

static size_t countLines(llvm::StringRef s) {
  if (s.empty())
    return 0;
  size_t n = 1;
  for (char c : s)
    if (c == '\n')
      ++n;
  return n;
}

static uint64_t getPeakRssBytes() {
  struct rusage ru {};
  if (::getrusage(RUSAGE_SELF, &ru) != 0)
    return 0;
#if defined(__APPLE__)
  return static_cast<uint64_t>(ru.ru_maxrss);
#else
  return static_cast<uint64_t>(ru.ru_maxrss) * 1024ull;
#endif
}

static uint64_t getCurrentRssBytes() {
#if defined(__APPLE__)
  mach_task_basic_info info {};
  mach_msg_type_number_t count = MACH_TASK_BASIC_INFO_COUNT;
  if (task_info(mach_task_self(), MACH_TASK_BASIC_INFO, reinterpret_cast<task_info_t>(&info), &count) != KERN_SUCCESS)
    return 0;
  return static_cast<uint64_t>(info.resident_size);
#elif defined(__linux__)
  std::ifstream in("/proc/self/statm");
  long totalPages = 0;
  long rssPages = 0;
  if (!(in >> totalPages >> rssPages))
    return 0;
  long pageSize = ::sysconf(_SC_PAGESIZE);
  if (pageSize <= 0)
    return 0;
  return static_cast<uint64_t>(rssPages) * static_cast<uint64_t>(pageSize);
#else
  return getPeakRssBytes();
#endif
}

static std::string md5HexOfString(llvm::StringRef s) {
  llvm::MD5 md5;
  md5.update(s);
  llvm::MD5::MD5Result res;
  md5.final(res);
  llvm::SmallString<32> hex;
  llvm::MD5::stringifyResult(res, hex);
  return hex.str().str();
}

static uint64_t computeComplexityScore(uint64_t lines, uint64_t bytes, llvm::StringRef kind) {
  uint64_t score = lines + (bytes / 64ull);
  if (kind == "tick")
    score = (score * 150ull) / 100ull;
  else if (kind == "eval")
    score = (score * 130ull) / 100ull;
  else if (kind == "comb")
    score = (score * 120ull) / 100ull;
  return score;
}

static double computePredictedCompileCost(uint64_t complexityScore, llvm::StringRef kind) {
  double w = 1.0;
  if (kind == "tick")
    w = 1.45;
  else if (kind == "eval")
    w = 1.25;
  else if (kind == "comb")
    w = 1.15;
  return static_cast<double>(complexityScore) * w;
}

struct InlinePolicyDecision {
  bool enableInline = true;
  std::string mode = "default";
  uint64_t thresholdOps = 0;
  std::string reason;
};

static uint64_t countModuleOps(ModuleOp module) {
  uint64_t ops = 0;
  module.walk([&](Operation *) { ++ops; });
  return ops;
}

class PassTimingCollector final : public mlir::PassInstrumentation {
public:
  struct Entry {
    uint64_t runs = 0;
    uint64_t totalMs = 0;
    uint64_t maxMs = 0;
    uint64_t maxRssBytes = 0;
  };

  void runBeforePass(mlir::Pass *pass, mlir::Operation *) override {
    Active a;
    a.name = pass ? pass->getName().str() : "<unknown-pass>";
    a.start = std::chrono::steady_clock::now();
    stack.push_back(std::move(a));
  }

  void runAfterPass(mlir::Pass *pass, mlir::Operation *) override { finalize(pass); }

  void runAfterPassFailed(mlir::Pass *pass, mlir::Operation *) override { finalize(pass); }

  llvm::json::Array toJson() const {
    std::vector<std::pair<std::string, Entry>> rows;
    rows.reserve(stats.size());
    for (const auto &kv : stats)
      rows.emplace_back(kv.first, kv.second);
    std::sort(rows.begin(), rows.end(), [](const auto &a, const auto &b) {
      if (a.second.totalMs != b.second.totalMs)
        return a.second.totalMs > b.second.totalMs;
      return a.first < b.first;
    });

    llvm::json::Array arr;
    for (const auto &kv : rows) {
      llvm::json::Object obj;
      obj["name"] = kv.first;
      obj["runs"] = static_cast<int64_t>(kv.second.runs);
      obj["total_ms"] = static_cast<int64_t>(kv.second.totalMs);
      obj["max_ms"] = static_cast<int64_t>(kv.second.maxMs);
      obj["max_rss_bytes"] = static_cast<int64_t>(kv.second.maxRssBytes);
      arr.push_back(std::move(obj));
    }
    return arr;
  }

private:
  struct Active {
    std::string name;
    std::chrono::steady_clock::time_point start;
  };

  void finalize(mlir::Pass *pass) {
    if (stack.empty())
      return;
    Active a = std::move(stack.back());
    stack.pop_back();
    if (pass) {
      std::string passName = pass->getName().str();
      if (!passName.empty())
        a.name = passName;
    }
    auto now = std::chrono::steady_clock::now();
    uint64_t ms = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(now - a.start).count());
    Entry &e = stats[a.name];
    e.runs += 1;
    e.totalMs += ms;
    e.maxMs = std::max(e.maxMs, ms);
    e.maxRssBytes = std::max(e.maxRssBytes, getCurrentRssBytes());
  }

  std::vector<Active> stack;
  std::unordered_map<std::string, Entry> stats;
};

static size_t findMatchingParen(llvm::StringRef s, size_t openPos) {
  if (openPos >= s.size() || s[openPos] != '(')
    return std::string::npos;
  int depth = 0;
  for (size_t i = openPos; i < s.size(); ++i) {
    char c = s[i];
    if (c == '(')
      ++depth;
    else if (c == ')') {
      --depth;
      if (depth == 0)
        return i;
    }
  }
  return std::string::npos;
}

static size_t findMatchingBraceSimple(llvm::StringRef s, size_t openPos) {
  if (openPos >= s.size() || s[openPos] != '{')
    return std::string::npos;
  int depth = 0;
  bool inLineComment = false;
  bool inBlockComment = false;
  bool inString = false;
  bool inChar = false;
  bool escape = false;
  for (size_t i = openPos; i < s.size(); ++i) {
    char c = s[i];
    char n = (i + 1 < s.size()) ? s[i + 1] : '\0';

    if (inLineComment) {
      if (c == '\n')
        inLineComment = false;
      continue;
    }
    if (inBlockComment) {
      if (c == '*' && n == '/') {
        inBlockComment = false;
        ++i;
      }
      continue;
    }
    if (inString) {
      if (escape) {
        escape = false;
      } else if (c == '\\') {
        escape = true;
      } else if (c == '"') {
        inString = false;
      }
      continue;
    }
    if (inChar) {
      if (escape) {
        escape = false;
      } else if (c == '\\') {
        escape = true;
      } else if (c == '\'') {
        inChar = false;
      }
      continue;
    }

    if (c == '/' && n == '/') {
      inLineComment = true;
      ++i;
      continue;
    }
    if (c == '/' && n == '*') {
      inBlockComment = true;
      ++i;
      continue;
    }
    if (c == '"') {
      inString = true;
      escape = false;
      continue;
    }
    if (c == '\'') {
      inChar = true;
      escape = false;
      continue;
    }
    if (c == '{')
      ++depth;
    else if (c == '}') {
      --depth;
      if (depth == 0)
        return i;
    }
  }
  return std::string::npos;
}

static bool startsWithWord(llvm::StringRef s, llvm::StringRef w) {
  if (!s.starts_with(w))
    return false;
  if (s.size() == w.size())
    return true;
  return std::isspace(static_cast<unsigned char>(s[w.size()])) != 0;
}

static std::string dropCtorInitializerForDecl(llvm::StringRef sig) {
  size_t p = sig.find('(');
  if (p == std::string::npos)
    return sig.str();
  size_t close = findMatchingParen(sig, p);
  if (close == std::string::npos)
    return sig.str();
  size_t colon = std::string::npos;
  for (size_t i = close + 1; i < sig.size(); ++i) {
    if (sig[i] == ':' && !(i > 0 && sig[i - 1] == ':') && !(i + 1 < sig.size() && sig[i + 1] == ':')) {
      colon = i;
      break;
    }
  }
  if (colon == std::string::npos)
    return sig.str();
  return trimCopy(sig.substr(0, colon));
}

static std::string removeDefaultArgs(llvm::StringRef sig) {
  size_t open = sig.find('(');
  if (open == std::string::npos)
    return sig.str();
  size_t close = findMatchingParen(sig, open);
  if (close == std::string::npos)
    return sig.str();

  std::string out;
  out.reserve(sig.size());
  out.append(sig.substr(0, open + 1).str());
  bool skipping = false;
  int depthParen = 0;
  int depthAngle = 0;
  int depthBrace = 0;
  int depthBracket = 0;
  for (size_t i = open + 1; i < close; ++i) {
    char c = sig[i];
    if (!skipping) {
      if (c == '(')
        ++depthParen;
      else if (c == ')')
        --depthParen;
      else if (c == '<')
        ++depthAngle;
      else if (c == '>')
        --depthAngle;
      else if (c == '{')
        ++depthBrace;
      else if (c == '}')
        --depthBrace;
      else if (c == '[')
        ++depthBracket;
      else if (c == ']')
        --depthBracket;

      if (c == '=' && depthParen == 0 && depthAngle == 0 && depthBrace == 0 && depthBracket == 0) {
        skipping = true;
        continue;
      }
      out.push_back(c);
    } else {
      if (c == '(')
        ++depthParen;
      else if (c == ')')
        --depthParen;
      else if (c == '<')
        ++depthAngle;
      else if (c == '>')
        --depthAngle;
      else if (c == '{')
        ++depthBrace;
      else if (c == '}')
        --depthBrace;
      else if (c == '[')
        ++depthBracket;
      else if (c == ']')
        --depthBracket;

      if (c == ',' && depthParen == 0 && depthAngle == 0 && depthBrace == 0 && depthBracket == 0) {
        out.push_back(',');
        skipping = false;
      }
    }
  }
  out.push_back(')');
  out.append(sig.substr(close + 1).str());
  return out;
}

static std::pair<size_t, size_t> findMethodNameRange(llvm::StringRef sig) {
  size_t paren = sig.find('(');
  if (paren == std::string::npos || paren == 0)
    return {std::string::npos, std::string::npos};
  size_t end = paren;
  while (end > 0 && std::isspace(static_cast<unsigned char>(sig[end - 1])))
    --end;
  size_t start = end;
  while (start > 0) {
    char c = sig[start - 1];
    if (std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == ':' || c == '~')
      --start;
    else
      break;
  }
  if (start == end)
    return {std::string::npos, std::string::npos};
  return {start, end};
}

static std::string methodKindForName(llvm::StringRef shortName) {
  if (shortName.starts_with("eval_comb_"))
    return "comb";
  if (shortName == "eval" || shortName == "eval_comb_pass" || shortName.starts_with("eval_"))
    return "eval";
  if (shortName.starts_with("tick"))
    return "tick";
  return "core";
}

static std::optional<SplitMethodDef> convertMethodChunk(llvm::StringRef chunk, llvm::StringRef structName,
                                                         std::string &error) {
  size_t open = chunk.find('{');
  if (open == std::string::npos) {
    error = "missing '{' in method chunk";
    return std::nullopt;
  }
  size_t close = findMatchingBraceSimple(chunk, open);
  if (close == std::string::npos) {
    error = "missing matching '}' in method chunk";
    return std::nullopt;
  }

  std::string signature = normalizeWhitespace(chunk.substr(0, open));
  std::string body = chunk.substr(open, close - open + 1).str();
  if (signature.empty()) {
    error = "empty method signature";
    return std::nullopt;
  }

  std::string declSig = signature;
  if (startsWithWord(declSig, "inline"))
    declSig = trimCopy(llvm::StringRef(declSig).drop_front(strlen("inline")));
  declSig = dropCtorInitializerForDecl(declSig);
  declSig = trimCopy(declSig);

  std::string defSig = signature;
  if (startsWithWord(defSig, "inline"))
    defSig = trimCopy(llvm::StringRef(defSig).drop_front(strlen("inline")));
  if (startsWithWord(defSig, "static"))
    defSig = trimCopy(llvm::StringRef(defSig).drop_front(strlen("static")));
  defSig = removeDefaultArgs(defSig);
  defSig = trimCopy(defSig);

  auto [nameStart, nameEnd] = findMethodNameRange(defSig);
  if (nameStart == std::string::npos || nameEnd == std::string::npos || nameEnd <= nameStart) {
    error = "failed to locate method name in signature: " + defSig;
    return std::nullopt;
  }
  std::string fullName = trimCopy(llvm::StringRef(defSig).substr(nameStart, nameEnd - nameStart));
  if (fullName.empty()) {
    error = "empty method name";
    return std::nullopt;
  }
  std::string shortName = fullName;
  if (size_t p = shortName.rfind("::"); p != std::string::npos)
    shortName = shortName.substr(p + 2);

  std::string qualifiedSig;
  qualifiedSig.reserve(defSig.size() + structName.size() + 2);
  qualifiedSig.append(defSig.substr(0, nameStart));
  if (fullName.find("::") == std::string::npos) {
    qualifiedSig.append(structName.str());
    qualifiedSig.append("::");
    qualifiedSig.append(fullName);
  } else {
    qualifiedSig.append(fullName);
  }
  qualifiedSig.append(defSig.substr(nameEnd));

  SplitMethodDef out;
  out.name = shortName;
  out.declaration = "  " + declSig + ";\n";
  out.definition = qualifiedSig + " " + body + "\n";
  out.kind = methodKindForName(shortName);
  out.bytes = out.definition.size();
  out.lines = countLines(out.definition);
  return out;
}

static bool isMethodStartLine(llvm::StringRef line, llvm::StringRef structName) {
  std::string t = trimCopy(line);
  if (t.empty())
    return false;
  if (startsWithWord(t, "struct") || startsWithWord(t, "class") || startsWithWord(t, "enum"))
    return false;
  if (t.find('(') == std::string::npos)
    return false;
  if (t.size() >= 2 && t[0] == '/' && t[1] == '/')
    return false;
  if (!(startsWithWord(t, "inline") || startsWithWord(t, "void") || startsWithWord(t, "static") ||
        startsWithWord(t, "bool") || startsWithWord(t, structName) || startsWithWord(t, "~" + structName.str()))) {
    return false;
  }
  size_t semi = t.find(';');
  size_t brace = t.find('{');
  if (semi != std::string::npos && (brace == std::string::npos || semi < brace))
    return false;
  return true;
}

static std::optional<SplitModuleResult> splitEmittedModule(llvm::StringRef emitted, llvm::StringRef structName,
                                                            std::string &error) {
  size_t structPos = emitted.find("struct " + structName.str());
  if (structPos == std::string::npos) {
    error = "cannot locate struct `" + structName.str() + "` in emitted text";
    return std::nullopt;
  }
  size_t open = emitted.find('{', structPos);
  if (open == std::string::npos) {
    error = "cannot locate struct open brace";
    return std::nullopt;
  }
  size_t close = findMatchingBraceSimple(emitted, open);
  if (close == std::string::npos) {
    error = "cannot locate struct close brace";
    return std::nullopt;
  }

  llvm::StringRef body = emitted.substr(open + 1, close - open - 1);
  SplitModuleResult out;
  out.headerBody.reserve(body.size() / 2);
  out.headerBody.append("struct ");
  out.headerBody.append(structName.str());
  out.headerBody.append(" {\n");

  // Template member functions must remain header-only (their definitions may
  // depend on call-site-only types like lambdas). The split algorithm below
  // cannot safely hoist such methods into a .cpp, so we detect a preceding
  // `template<...>` line and preserve the following method definition inline.
  bool pendingTemplate = false;

  size_t cursor = 0;
  while (cursor < body.size()) {
    size_t lineEnd = body.find('\n', cursor);
    size_t next = (lineEnd == std::string::npos) ? body.size() : (lineEnd + 1);
    llvm::StringRef line = body.slice(cursor, next);

    std::string trimmed = trimCopy(line);
    if (startsWithWord(trimmed, "template")) {
      pendingTemplate = true;
      out.headerBody.append(line.str());
      cursor = next;
      continue;
    }

    if (isMethodStartLine(line, structName)) {
      size_t methodStart = cursor;
      size_t methodOpen = body.find('{', methodStart);
      if (methodOpen == std::string::npos) {
        error = "method start without body brace";
        return std::nullopt;
      }
      if (lineEnd != std::string::npos && methodOpen > lineEnd) {
        size_t search = next;
        while (methodOpen == std::string::npos && search < body.size()) {
          size_t le = body.find('\n', search);
          size_t nx = (le == std::string::npos) ? body.size() : (le + 1);
          methodOpen = body.find('{', search);
          if (methodOpen != std::string::npos && (le == std::string::npos || methodOpen <= le))
            break;
          search = nx;
        }
      }
      if (methodOpen == std::string::npos) {
        error = "method signature without opening brace";
        return std::nullopt;
      }
      size_t methodClose = findMatchingBraceSimple(body, methodOpen);
      if (methodClose == std::string::npos) {
        error = "unterminated method body";
        return std::nullopt;
      }
      llvm::StringRef chunk = body.slice(methodStart, methodClose + 1);
      if (pendingTemplate) {
        out.headerBody.append(chunk.str());
        out.headerBody.push_back('\n');
      } else {
        auto converted = convertMethodChunk(chunk, structName, error);
        if (!converted)
          return std::nullopt;
        out.headerBody.append(converted->declaration);
        out.headerBody.push_back('\n');
        out.methods.push_back(std::move(*converted));
      }
      pendingTemplate = false;

      cursor = methodClose + 1;
      while (cursor < body.size() && (body[cursor] == '\r' || body[cursor] == '\n'))
        ++cursor;
      continue;
    }

    out.headerBody.append(line.str());
    if (!trimmed.empty() && !(trimmed.size() >= 2 && trimmed[0] == '/' && trimmed[1] == '/')) {
      // Any non-comment, non-empty line breaks template adjacency.
      pendingTemplate = false;
    }
    cursor = next;
  }

  out.headerBody.append("};\n");
  return out;
}

static LogicalResult writeCppCompileManifest(llvm::StringRef path,
                                             llvm::StringRef targetName,
                                             llvm::ArrayRef<CppManifestSource> sources,
                                             llvm::ArrayRef<std::string> includeDirs,
                                             llvm::ArrayRef<std::string> compileDefines,
                                             std::optional<std::string> toolchainRoot,
                                             llvm::StringRef topHeader,
                                             const llvm::json::Object &profileSummary) {
  llvm::json::Object manifest;
  manifest["version"] = 3;
  manifest["target_name"] = targetName.str();
  manifest["cxx_standard"] = "c++17";

  llvm::json::Array includeDirsJson;
  for (const auto &p : includeDirs)
    includeDirsJson.push_back(p);
  manifest["include_dirs"] = std::move(includeDirsJson);

  llvm::json::Array definesJson;
  for (const auto &d : compileDefines)
    definesJson.push_back(d);
  manifest["compile_defines"] = std::move(definesJson);

  llvm::json::Array srcJson;
  std::vector<std::string> hashParts;
  hashParts.reserve(sources.size() + 2);
  hashParts.push_back(targetName.str());
  hashParts.push_back(topHeader.str());
  for (const auto &s : sources) {
    llvm::json::Object obj;
    obj["path"] = s.path;
    obj["module"] = s.module;
    obj["shard"] = s.shard;
    obj["kind"] = s.kind;
    obj["probe_only"] = s.probeOnly;
    obj["bytes"] = static_cast<int64_t>(s.bytes);
    obj["lines"] = static_cast<int64_t>(s.lines);
    obj["complexity_score"] = static_cast<int64_t>(s.complexityScore);
    obj["predicted_compile_cost"] = s.predictedCompileCost;
    obj["source_hash"] = s.sourceHash;
    srcJson.push_back(std::move(obj));
    hashParts.push_back(
        s.path + "|" + s.module + "|" + s.shard + "|" + s.kind + "|" + (s.probeOnly ? "1" : "0") +
        "|" + std::to_string(s.bytes) + "|" + std::to_string(s.lines) +
        "|" + std::to_string(s.complexityScore) + "|" + s.sourceHash);
  }
  manifest["sources"] = std::move(srcJson);
  if (toolchainRoot) {
    llvm::json::Object runtime;
    runtime["mode"] = "prebuilt";
    runtime["cmake_package"] = "pycircuit";
    runtime["cmake_target"] = "pycircuit::pyc4_runtime";
    runtime["toolchain_root_hint"] = *toolchainRoot;

    llvm::SmallString<256> cmakeCfgDir(*toolchainRoot);
    llvm::sys::path::append(cmakeCfgDir, "share", "pycircuit", "cmake");
    runtime["cmake_config_dir"] = cmakeCfgDir.str().str();

    llvm::json::Array runtimeIncludeDirs;
    llvm::SmallString<256> includeDir(*toolchainRoot);
    llvm::sys::path::append(includeDir, "include");
    runtimeIncludeDirs.push_back(includeDir.str().str());
    runtime["include_dirs"] = std::move(runtimeIncludeDirs);

    llvm::json::Array runtimeLibDirs;
    llvm::SmallString<256> libDir(*toolchainRoot);
    llvm::sys::path::append(libDir, "lib");
    runtimeLibDirs.push_back(libDir.str().str());
    runtime["lib_dirs"] = std::move(runtimeLibDirs);

    llvm::json::Array runtimeLibs;
    runtimeLibs.push_back("pyc4_runtime");
    runtime["libs"] = std::move(runtimeLibs);

    llvm::json::Array runtimeLibraryFiles;
    llvm::SmallString<256> runtimeLib(*toolchainRoot);
    llvm::sys::path::append(runtimeLib, "lib", runtimeLibBasename());
    runtimeLibraryFiles.push_back(runtimeLib.str().str());
    runtime["library_files"] = std::move(runtimeLibraryFiles);

    manifest["runtime"] = std::move(runtime);
  }
  manifest["top_header"] = topHeader.str();
  manifest["profile_summary"] = llvm::json::Object(profileSummary);

  std::string hashInput;
  hashInput.reserve(256);
  for (const auto &part : hashParts) {
    hashInput.append(part);
    hashInput.push_back('\n');
  }
  llvm::MD5 md5;
  md5.update(hashInput);
  llvm::MD5::MD5Result md5Result;
  md5.final(md5Result);
  llvm::SmallString<32> md5Hex;
  llvm::MD5::stringifyResult(md5Result, md5Hex);
  manifest["deterministic_hash"] = md5Hex.str().str();

  std::string buf;
  llvm::raw_string_ostream ss(buf);
  llvm::json::OStream j(ss, 2);
  llvm::json::Value v(std::move(manifest));
  j.value(v);
  ss << "\n";
  ss.flush();
  return writeFile(path, buf);
}

struct CompileStatsSummary {
  int64_t regCount = 0;
  int64_t regBits = 0;
  int64_t memCount = 0;
  int64_t memBits = 0;
  int64_t maxLogicDepth = 0;
  int64_t wns = 0;
  int64_t tns = 0;
  int64_t logicDepthLimit = 32;
  bool fuseCombEnabled = false;
};

static int64_t getI64Attr(Operation *op, llvm::StringRef name, int64_t fallback = 0) {
  if (auto attr = op->getAttrOfType<IntegerAttr>(name))
    return static_cast<int64_t>(attr.getInt());
  return fallback;
}

static int64_t satAdd(int64_t a, int64_t b) {
  __int128 v = static_cast<__int128>(a) + static_cast<__int128>(b);
  if (v > std::numeric_limits<int64_t>::max())
    return std::numeric_limits<int64_t>::max();
  if (v < std::numeric_limits<int64_t>::min())
    return std::numeric_limits<int64_t>::min();
  return static_cast<int64_t>(v);
}

static CompileStatsSummary collectCompileStats(ModuleOp module, int64_t depthLimit) {
  CompileStatsSummary s;
  s.logicDepthLimit = depthLimit;
  bool sawWns = false;
  s.wns = depthLimit;

  for (auto f : module.getOps<func::FuncOp>()) {
    s.regCount = satAdd(s.regCount, getI64Attr(f, "pyc.stats.reg_count", 0));
    s.regBits = satAdd(s.regBits, getI64Attr(f, "pyc.stats.reg_bits", 0));
    s.memCount = satAdd(s.memCount, getI64Attr(f, "pyc.stats.mem_count", 0));
    s.memBits = satAdd(s.memBits, getI64Attr(f, "pyc.stats.mem_bits", 0));

    s.maxLogicDepth = std::max(s.maxLogicDepth, getI64Attr(f, "pyc.logic_depth.max", 0));

    int64_t fWns = getI64Attr(f, "pyc.logic_depth.wns", depthLimit);
    if (!sawWns) {
      s.wns = fWns;
      sawWns = true;
    } else {
      s.wns = std::min(s.wns, fWns);
    }
    s.tns = satAdd(s.tns, getI64Attr(f, "pyc.logic_depth.tns", 0));
  }

  if (!sawWns)
    s.wns = depthLimit;
  return s;
}

static void printCompileStats(const CompileStatsSummary &s) {
  llvm::errs() << "stats: regs=" << s.regCount << " (" << s.regBits << " bits)"
               << ", mems=" << s.memCount << " (" << s.memBits << " bits)"
               << ", max_depth=" << s.maxLogicDepth << "/" << s.logicDepthLimit
               << ", WNS=" << s.wns << ", TNS=" << s.tns
               << ", fuse_comb=" << (s.fuseCombEnabled ? "on" : "off") << "\n";
}

static LogicalResult writeCompileStatsJson(llvm::StringRef outPath, const CompileStatsSummary &s) {
  llvm::json::Object obj;
  obj["reg_count"] = s.regCount;
  obj["reg_bits"] = s.regBits;
  obj["mem_count"] = s.memCount;
  obj["mem_bits"] = s.memBits;
  obj["logic_depth_limit"] = s.logicDepthLimit;
  obj["max_logic_depth"] = s.maxLogicDepth;
  obj["wns"] = s.wns;
  obj["tns"] = s.tns;
  obj["fuse_comb_enabled"] = s.fuseCombEnabled;

  std::string buf;
  llvm::raw_string_ostream ss(buf);
  llvm::json::OStream j(ss, 2);
  llvm::json::Value v(std::move(obj));
  j.value(v);
  ss << "\n";
  ss.flush();
  return writeFile(outPath, buf);
}

static LogicalResult writeProfileJson(llvm::StringRef outPath, const llvm::json::Object &profile) {
  std::string buf;
  llvm::raw_string_ostream ss(buf);
  llvm::json::OStream j(ss, 2);
  llvm::json::Object obj(profile);
  llvm::json::Value v(std::move(obj));
  j.value(v);
  ss << "\n";
  ss.flush();
  return writeFile(outPath, buf);
}

int main(int argc, char **argv) {
  llvm::InitLLVM y(argc, argv);
  llvm::cl::ParseCommandLineOptions(argc, argv, "pycc\n");
  using Clock = std::chrono::steady_clock;
  const auto tProgramStart = Clock::now();
  uint64_t parseMs = 0;
  uint64_t passMs = 0;
  uint64_t emitMs = 0;

  const bool hasDirectCpp = !directCppOut.empty();
  const bool hasDirectVerilog = !directVerilogOut.empty();
  if (hasDirectCpp && hasDirectVerilog) {
    llvm::errs() << "error: `-cpp` and `-verilog` are mutually exclusive\n";
    return 1;
  }
  if (hasDirectCpp) {
    emitKind = "cpp";
    outputFilename = std::string(directCppOut);
  }
  if (hasDirectVerilog) {
    emitKind = "verilog";
    outputFilename = std::string(directVerilogOut);
  }
  if ((hasDirectCpp || hasDirectVerilog) && !outDir.empty()) {
    llvm::errs() << "error: direct output mode (-cpp/-verilog) cannot be combined with --out-dir\n";
    return 1;
  }
  if ((hasDirectCpp || hasDirectVerilog) && outputFilename.empty()) {
    llvm::errs() << "error: direct output mode requires a non-empty output path\n";
    return 1;
  }

  std::string buildProfileNorm = llvm::StringRef(buildProfile).lower();
  if (buildProfileNorm != "release" && buildProfileNorm != "dev-fast") {
    llvm::errs() << "error: unknown --build-profile: " << buildProfile
                 << " (expected: release|dev-fast)\n";
    return 1;
  }
  const bool isDevFastProfile = (buildProfileNorm == "dev-fast");

  // Dev-fast defaults to smaller C++ shards unless explicitly overridden.
  if (isDevFastProfile && cppShardThresholdLines.getNumOccurrences() == 0)
    cppShardThresholdLines = 16000;
  if (isDevFastProfile && cppShardThresholdBytes.getNumOccurrences() == 0)
    cppShardThresholdBytes = 768 * 1024;
  if (isDevFastProfile && cppShardMaxAstNodes.getNumOccurrences() == 0)
    cppShardMaxAstNodes = 192;

  std::string profileJsonPathResolved = profileJsonPath;
  if (profileJsonPathResolved.empty() && profilePassTiming) {
    if (!outDir.empty()) {
      llvm::SmallString<256> p(outDir);
      llvm::sys::path::append(p, "pycc_profile.json");
      profileJsonPathResolved = p.str().str();
    } else if (outputFilename != "-") {
      profileJsonPathResolved = (llvm::Twine(outputFilename) + ".profile.json").str();
    }
  }
  const bool collectPassTiming = profilePassTiming || !profileJsonPathResolved.empty();

  DialectRegistry registry;
  registry.insert<pyc::PYCDialect, mlir::arith::ArithDialect, mlir::func::FuncDialect, mlir::scf::SCFDialect>();
  mlir::func::registerInlinerExtension(registry);

  MLIRContext ctx(registry);
#ifdef _WIN32
  // MSYS2/MinGW builds can hit non-deterministic crashes when running nested
  // pass pipelines with multithreading enabled. Bring-up prefers robustness.
  ctx.disableMultithreading();
#endif
  ctx.loadAllAvailableDialects();

  const auto tParseStart = Clock::now();
  llvm::SourceMgr sm;
  auto fileOrErr = llvm::MemoryBuffer::getFileOrSTDIN(inputFilename);
  if (!fileOrErr) {
    llvm::errs() << "error: cannot read " << inputFilename << "\n";
    return 1;
  }
  sm.AddNewSourceBuffer(std::move(*fileOrErr), llvm::SMLoc());

  OwningOpRef<ModuleOp> module = parseSourceFile<ModuleOp>(sm, &ctx);
  if (!module) {
    llvm::errs() << "error: failed to parse MLIR\n";
    return 1;
  }
  parseMs = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tParseStart).count());
  uint64_t moduleOpCount = countModuleOps(*module);

  // Host-side testbench payload modules are emitted directly without hardware
  // lowering passes.
  if (getTbPayloadAttr(*module).has_value()) {
    if (!outDir.empty()) {
      llvm::errs() << "error: testbench payload mode does not support --out-dir; use direct -cpp/-verilog or -o\n";
      return 1;
    }
    std::error_code ec;
    llvm::raw_fd_ostream os(outputFilename, ec, llvm::sys::fs::OF_Text);
    if (ec) {
      llvm::errs() << "error: cannot open " << outputFilename << ": " << ec.message() << "\n";
      return 1;
    }
    if (failed(emitTbTextFromPayload(*module, emitKind, os)))
      return 1;
    return 0;
  }

  bool cppOnly = false;
  if (simMode == "default") {
    cppOnly = false;
  } else if (simMode == "cpp-only") {
    cppOnly = true;
  } else {
    llvm::errs() << "error: unknown --sim-mode: " << simMode << " (expected: default|cpp-only)\n";
    return 1;
  }

  if (emitStructuralMode != "auto" && emitStructuralMode != "on" && emitStructuralMode != "off") {
    llvm::errs() << "error: unknown --emit-structural: " << emitStructuralMode << " (expected: auto|on|off)\n";
    return 1;
  }
  if (emitStructuralMode == "on" || emitStructuralMode == "off") {
    bool enableStructural = (emitStructuralMode == "on");
    for (func::FuncOp f : module->getOps<func::FuncOp>()) {
      if (enableStructural)
        f->setAttr("pyc.emit.structural", StringAttr::get(&ctx, "true"));
      else
        f->removeAttr("pyc.emit.structural");
    }
  }

  bool strictHierarchy = true;
  if (hierarchyPolicy != "strict") {
    llvm::errs() << "error: unknown --hierarchy-policy: " << hierarchyPolicy
                 << " (expected: strict)\n";
    return 1;
  }

  const std::set<std::string> moduleSymbolsBefore = collectFrontendModuleSymbols(*module);

  InlinePolicyDecision inlineDecision;
  inlineDecision.mode = inlinePolicy;
  bool forceNoInline = noInline;
  if (forceNoInline) {
    inlineDecision.enableInline = false;
    inlineDecision.reason = "cli --noinline";
  } else if (inlinePolicy == "default") {
    if (strictHierarchy) {
      inlineDecision.enableInline = false;
      inlineDecision.reason = "strict hierarchy default";
    } else if (isDevFastProfile) {
      inlineDecision.enableInline = false;
      inlineDecision.reason = "dev-fast default";
    } else {
      inlineDecision.enableInline = true;
      inlineDecision.reason = "release default";
    }
  } else if (inlinePolicy == "off") {
    inlineDecision.enableInline = false;
    inlineDecision.reason = "inline-policy=off";
  } else if (llvm::StringRef(inlinePolicy).starts_with("threshold:")) {
    llvm::StringRef n = llvm::StringRef(inlinePolicy).drop_front(strlen("threshold:"));
    uint64_t threshold = 0;
    if (n.getAsInteger(10, threshold) || threshold == 0) {
      llvm::errs() << "error: invalid --inline-policy threshold, expected threshold:<positive-int>\n";
      return 1;
    }
    inlineDecision.mode = "threshold";
    inlineDecision.thresholdOps = threshold;
    inlineDecision.enableInline = moduleOpCount <= threshold;
    inlineDecision.reason = inlineDecision.enableInline ? "module-op-count <= threshold" : "module-op-count > threshold";
  } else {
    llvm::errs() << "error: unknown --inline-policy: " << inlinePolicy
                 << " (expected: default|off|threshold:<n>)\n";
    return 1;
  }

  // Strict hierarchy is a hard non-inline policy: the frontend module graph
  // must remain explicit and unflattened.
  if (strictHierarchy && inlineDecision.enableInline) {
    llvm::errs() << "error: strict hierarchy requires non-inline module compilation\n";
    llvm::errs() << "  inline_policy=" << inlineDecision.mode
                 << " enables inliner (reason: " << inlineDecision.reason << ")\n";
    llvm::errs() << "  hint: use --inline-policy=off (or --inline-policy=default with --hierarchy-policy=strict)\n";
    return 1;
  }

  unsigned effectiveCanonicalizeBudget = canonicalizeBudget;
  if (effectiveCanonicalizeBudget == 0 && isDevFastProfile)
    effectiveCanonicalizeBudget = 6;

  GreedyRewriteConfig canonicalizeCfg;
  if (effectiveCanonicalizeBudget > 0) {
    canonicalizeCfg.maxIterations = static_cast<int64_t>(effectiveCanonicalizeBudget);
    canonicalizeCfg.maxNumRewrites = static_cast<int64_t>(effectiveCanonicalizeBudget) * 4096;
  }

  // Cleanup + optimization pipeline tuned for netlist-style emission.
  PassManager pm(&ctx);
  std::unique_ptr<PassTimingCollector> passTimingStorage;
  PassTimingCollector *passTimingCollector = nullptr;
  if (collectPassTiming) {
    passTimingStorage = std::make_unique<PassTimingCollector>();
    passTimingCollector = passTimingStorage.get();
    pm.addInstrumentation(std::move(passTimingStorage));
  }
  pm.addPass(pyc::createCheckFrontendContractPass());
  pm.addPass(pyc::createInlineFunctionsPass());
  pm.addPass(pyc::createCheckHierarchyDisciplinePass());
  pm.addPass(createSymbolDCEPass());
  if (inlineDecision.enableInline)
    pm.addPass(createInlinerPass());
  pm.addPass(createCanonicalizerPass(canonicalizeCfg));
  pm.addPass(createCSEPass());
  pm.addPass(createSCCPPass());
  addRemoveDeadValuesPassIfSupported(pm);
  pm.addNestedPass<func::FuncOp>(pyc::createEliminateDeadInstancesPass());
  pm.addPass(createSymbolDCEPass());

  pm.addNestedPass<func::FuncOp>(pyc::createLowerSCFToPYCStaticPass());
  pm.addNestedPass<func::FuncOp>(pyc::createEliminateWiresPass());
  pm.addNestedPass<func::FuncOp>(pyc::createEliminateDeadStatePass());
  pm.addNestedPass<func::FuncOp>(pyc::createCombCanonicalizePass());
  pm.addNestedPass<func::FuncOp>(pyc::createSLPPackWiresPass());
  pm.addPass(pyc::createCheckCombCyclesPass());
  pm.addPass(pyc::createCheckClockDomainsPass());
  pm.addNestedPass<func::FuncOp>(pyc::createPackI1RegsPass());
  const bool enableFuseComb = (!cppOnly) || !cppOnlyPreserveOps;
  if (enableFuseComb)
    pm.addNestedPass<func::FuncOp>(pyc::createFuseCombPass());
  pm.addPass(createCanonicalizerPass(canonicalizeCfg));
  pm.addPass(createCSEPass());
  addRemoveDeadValuesPassIfSupported(pm);
  pm.addNestedPass<func::FuncOp>(pyc::createEliminateDeadInstancesPass());
  pm.addPass(createSymbolDCEPass());
  pm.addNestedPass<func::FuncOp>(pyc::createCheckFlatTypesPass());
  pm.addNestedPass<func::FuncOp>(pyc::createCheckNoDynamicPass());
  pm.addPass(pyc::createCheckLogicDepthPass(logicDepthLimit));
  pm.addNestedPass<func::FuncOp>(pyc::createCollectCompileStatsPass());
  const auto tPassStart = Clock::now();
  if (failed(pm.run(*module))) {
    llvm::errs() << "error: pass pipeline failed\n";
    return 1;
  }
  passMs = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tPassStart).count());

  const std::set<std::string> moduleSymbolsAfter = collectFrontendModuleSymbols(*module);
  const bool hierarchyPreserved = (moduleSymbolsBefore == moduleSymbolsAfter);
  if (strictHierarchy && !hierarchyPreserved) {
    llvm::errs() << "error: strict hierarchy policy violation: frontend module symbol set changed after passes\n";
    llvm::errs() << "  before_count=" << moduleSymbolsBefore.size()
                 << " after_count=" << moduleSymbolsAfter.size() << "\n";
    for (const auto &sym : moduleSymbolsBefore) {
      if (!moduleSymbolsAfter.count(sym))
        llvm::errs() << "  removed_module=" << sym << "\n";
    }
    for (const auto &sym : moduleSymbolsAfter) {
      if (!moduleSymbolsBefore.count(sym))
        llvm::errs() << "  added_module=" << sym << "\n";
    }
    return 1;
  }

  CompileStatsSummary compileStats = collectCompileStats(*module, static_cast<int64_t>(logicDepthLimit));
  compileStats.fuseCombEnabled = enableFuseComb;
  printCompileStats(compileStats);

  if (!probeManifestPath.empty()) {
    if (failed(emitProbeManifest(*module, probeManifestPath)))
      return 1;
  }

  auto writeSingleOutputStats = [&]() -> LogicalResult {
    if (outputFilename == "-")
      return success();
    llvm::SmallString<256> statsPath(outputFilename);
    statsPath += ".stats.json";
    return writeCompileStatsJson(statsPath, compileStats);
  };

  auto buildProfileSummary = [&]() -> llvm::json::Object {
    llvm::json::Object obj;
    obj["build_profile"] = buildProfileNorm;
    obj["hierarchy_policy"] = "strict";
    obj["module_count_before"] = static_cast<int64_t>(moduleSymbolsBefore.size());
    obj["module_count_after"] = static_cast<int64_t>(moduleSymbolsAfter.size());
    obj["hierarchy_preserved"] = hierarchyPreserved;
    obj["inline_policy"] = inlineDecision.mode;
    obj["inline_enabled"] = inlineDecision.enableInline;
    obj["inline_threshold_ops"] = static_cast<int64_t>(inlineDecision.thresholdOps);
    obj["inline_reason"] = inlineDecision.reason;
    obj["canonicalize_budget"] = static_cast<int64_t>(effectiveCanonicalizeBudget);
    obj["module_op_count"] = static_cast<int64_t>(moduleOpCount);
    obj["cpp_shard_threshold_lines"] = static_cast<int64_t>(cppShardThresholdLines);
    obj["cpp_shard_threshold_bytes"] = static_cast<int64_t>(cppShardThresholdBytes);
    obj["cpp_shard_max_ast_nodes"] = static_cast<int64_t>(cppShardMaxAstNodes);
    obj["profile_pass_timing"] = collectPassTiming;
    return obj;
  };

  auto writeProfileArtifact = [&](llvm::StringRef lane) -> LogicalResult {
    if (profileJsonPathResolved.empty())
      return success();
    llvm::json::Object root;
    root["version"] = 1;
    root["input"] = inputFilename;
    root["emit_kind"] = emitKind;
    root["lane"] = lane.str();
    root["build_profile"] = buildProfileNorm;
    root["module_op_count"] = static_cast<int64_t>(moduleOpCount);

    llvm::json::Object timing;
    timing["parse_ms"] = static_cast<int64_t>(parseMs);
    timing["passes_ms"] = static_cast<int64_t>(passMs);
    timing["emit_ms"] = static_cast<int64_t>(emitMs);
    timing["total_ms"] = static_cast<int64_t>(
        std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tProgramStart).count());
    root["timing"] = std::move(timing);

    llvm::json::Object memory;
    memory["peak_rss_bytes"] = static_cast<int64_t>(getPeakRssBytes());
    memory["current_rss_bytes"] = static_cast<int64_t>(getCurrentRssBytes());
    root["memory"] = std::move(memory);

    llvm::json::Object inlineObj;
    inlineObj["mode"] = inlineDecision.mode;
    inlineObj["enabled"] = inlineDecision.enableInline;
    inlineObj["threshold_ops"] = static_cast<int64_t>(inlineDecision.thresholdOps);
    inlineObj["reason"] = inlineDecision.reason;
    root["inline"] = std::move(inlineObj);
    llvm::json::Object hierarchyObj;
    hierarchyObj["policy"] = "strict";
    hierarchyObj["module_count_before"] = static_cast<int64_t>(moduleSymbolsBefore.size());
    hierarchyObj["module_count_after"] = static_cast<int64_t>(moduleSymbolsAfter.size());
    hierarchyObj["preserved"] = hierarchyPreserved;
    root["hierarchy"] = std::move(hierarchyObj);
    root["canonicalize_budget"] = static_cast<int64_t>(effectiveCanonicalizeBudget);

    llvm::json::Object stats;
    stats["reg_count"] = compileStats.regCount;
    stats["reg_bits"] = compileStats.regBits;
    stats["mem_count"] = compileStats.memCount;
    stats["mem_bits"] = compileStats.memBits;
    stats["logic_depth_limit"] = compileStats.logicDepthLimit;
    stats["max_logic_depth"] = compileStats.maxLogicDepth;
    stats["wns"] = compileStats.wns;
    stats["tns"] = compileStats.tns;
    stats["fuse_comb_enabled"] = compileStats.fuseCombEnabled;
    root["compile_stats"] = std::move(stats);

    if (passTimingCollector)
      root["passes"] = passTimingCollector->toJson();

    return writeProfileJson(profileJsonPathResolved, root);
  };

  const auto tEmitStart = Clock::now();
  if (emitKind == "none") {
    emitMs = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tEmitStart).count());
    if (failed(writeProfileArtifact("no-emit")))
      return 1;
    return 0;
  }
  if (!outDir.empty()) {
    std::error_code ec = llvm::sys::fs::create_directories(outDir);
    if (ec) {
      llvm::errs() << "error: cannot create --out-dir " << outDir << ": " << ec.message() << "\n";
      return 1;
    }

    std::string top = topSymbol(*module);
    if (top.empty()) {
      llvm::errs() << "error: cannot determine top symbol (missing pyc.top and no func.func)\n";
      return 1;
    }

    if (emitKind == "verilog") {
      if (cppOnly) {
        llvm::errs() << "error: --emit=verilog is not allowed with --sim-mode=cpp-only\n";
        return 1;
      }
      llvm::json::Array verilogFiles;
      bool targetFpga = (targetKind == "fpga");
      if (!targetFpga && targetKind != "default") {
        llvm::errs() << "error: unknown --target: " << targetKind << " (expected: default|fpga)\n";
        return 1;
      }
      if (includePrims) {
        auto primDir = findPrimitivesDir(argv[0]);
        if (!primDir) {
          llvm::errs() << "error: cannot locate runtime/verilog for primitives; set PYC_PRIMITIVES_DIR\n";
          return 1;
        }
        llvm::SmallString<256> primOut(outDir);
        llvm::sys::path::append(primOut, "pyc_primitives.v");
        if (failed(emitPrimitivesFile(primOut, *primDir, targetFpga)))
          return 1;
        verilogFiles.push_back("pyc_primitives.v");
      }

      pyc::VerilogEmitterOptions opts;
      opts.includePrimitives = false; // out-dir mode uses pyc_primitives.v (or expects external primitives)
      opts.targetFpga = targetFpga;

      for (auto f : module->getOps<func::FuncOp>()) {
        if (f.isDeclaration())
          continue;
        std::string fname = (f.getSymName() + ".v").str();
        llvm::SmallString<256> path(outDir);
        llvm::sys::path::append(path, fname);

        std::error_code fe;
        llvm::raw_fd_ostream os(path, fe, llvm::sys::fs::OF_Text);
        if (fe) {
          llvm::errs() << "error: cannot open " << path << ": " << fe.message() << "\n";
          return 1;
        }
        if (failed(pyc::emitVerilogFunc(*module, f, os, opts)))
          return 1;
        verilogFiles.push_back(fname);
      }

      if (failed(updateManifest(outDir, top, std::move(verilogFiles), /*cppMods=*/std::nullopt)))
        return 1;

      // Optional Yosys stub (sanity synth).
      llvm::SmallString<256> ysPath(outDir);
      llvm::sys::path::append(ysPath, "yosys_synth.ys");
      std::string ys;
      llvm::raw_string_ostream yss(ys);
      yss << "# Generated by pycc\n";
      if (includePrims)
        yss << "read_verilog -sv pyc_primitives.v\n";
      for (auto f : module->getOps<func::FuncOp>()) {
        if (f.isDeclaration())
          continue;
        yss << "read_verilog -sv " << f.getSymName().str() << ".v\n";
      }
      yss << "hierarchy -top " << top << "\n";
      yss << "proc; opt; memory; opt\n";
      yss << "synth -top " << top << "\n";
      yss.flush();
      if (failed(writeFile(ysPath, ys)))
        return 1;

      llvm::SmallString<256> statsPath(outDir);
      llvm::sys::path::append(statsPath, "compile_stats.json");
      if (failed(writeCompileStatsJson(statsPath, compileStats)))
        return 1;
      emitMs = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tEmitStart).count());
      if (failed(writeProfileArtifact("out-dir:verilog")))
        return 1;

      return 0;
    }

    if (emitKind == "cpp") {
      llvm::json::Array cppFiles;
      std::vector<CppManifestSource> cppManifestSources;
      pyc::CppEmitterOptions cppEmitOpts;
      if (cppShardMaxAstNodes > 0) {
        cppEmitOpts.evalTopoChunkNodes = cppShardMaxAstNodes;
        cppEmitOpts.combChunkNodes = cppShardMaxAstNodes;
      }
      cppEmitOpts.probePlanPath = probePlanPath;

      // Collect direct dependencies per module for header includes.
      llvm::StringMap<llvm::SmallVector<std::string>> deps;
      for (auto f : module->getOps<func::FuncOp>()) {
        if (f.isDeclaration())
          continue;
        auto &v = deps[f.getSymName()];
        f.walk([&](pyc::InstanceOp inst) {
          auto calleeAttr = inst->getAttrOfType<FlatSymbolRefAttr>("callee");
          if (!calleeAttr)
            return;
          v.push_back(calleeAttr.getValue().str());
        });
        std::sort(v.begin(), v.end());
        v.erase(std::unique(v.begin(), v.end()), v.end());
      }

      bool splitModule = false;
      if (cppSplitMode == "module")
        splitModule = true;
      else if (cppSplitMode == "none")
        splitModule = false;
      else {
        llvm::errs() << "error: unknown --cpp-split mode: " << cppSplitMode << " (expected: module|none)\n";
        return 1;
      }

      auto writeHeaderPreamble = [&](llvm::raw_ostream &os, llvm::StringRef moduleName) {
        (void)moduleName;
        os << "// pyCircuit C++ emission (split)\n";
        os << "#pragma once\n";
        os << "#include <cstdlib>\n";
        os << "#include <cstdint>\n";
        os << "#include <fstream>\n";
        os << "#include <iostream>\n";
        os << "#include <memory>\n";
        os << "#include <string>\n";
        os << "#include <cpp/pyc_sim.hpp>\n";
      };

      auto writeSourcePreamble = [&](llvm::raw_ostream &os, llvm::StringRef headerName) {
        os << "// pyCircuit C++ emission (split)\n";
        os << "#include \"" << headerName << "\"\n\n";
        os << "namespace pyc::gen {\n\n";
      };

      auto writeSourceEpilogue = [&](llvm::raw_ostream &os) { os << "} // namespace pyc::gen\n"; };

      for (auto f : module->getOps<func::FuncOp>()) {
        if (f.isDeclaration())
          continue;
        std::string moduleName = f.getSymName().str();
        const bool probeOnlyModule = isProbeOnlyFunc(f);
        std::string headerName = moduleName + ".hpp";
        llvm::SmallString<256> headerPath(outDir);
        llvm::sys::path::append(headerPath, headerName);

        std::string emitted;
        {
          llvm::raw_string_ostream emitOs(emitted);
          if (failed(pyc::emitCppFunc(*module, f, emitOs, cppEmitOpts)))
            return 1;
          emitOs.flush();
        }

        if (splitModule) {
          std::string splitErr;
          auto split = splitEmittedModule(emitted, moduleName, splitErr);
          if (!split) {
            llvm::errs() << "error: failed to split module `" << moduleName << "`: " << splitErr << "\n";
            return 1;
          }

          std::error_code fe;
          llvm::raw_fd_ostream hos(headerPath, fe, llvm::sys::fs::OF_Text);
          if (fe) {
            llvm::errs() << "error: cannot open " << headerPath << ": " << fe.message() << "\n";
            return 1;
          }
          writeHeaderPreamble(hos, moduleName);
          for (const std::string &dep : deps[f.getSymName()])
            hos << "#include \"" << dep << ".hpp\"\n";
          hos << "\nnamespace pyc::gen {\n\n";
          hos << split->headerBody << "\n";
          hos << "} // namespace pyc::gen\n";

          auto writeSourceFile = [&](llvm::StringRef fileName,
                                     llvm::StringRef kind,
                                     llvm::StringRef shard,
                                     llvm::ArrayRef<const SplitMethodDef *> defs) -> LogicalResult {
            if (defs.empty())
              return success();
            llvm::SmallString<256> srcPath(outDir);
            llvm::sys::path::append(srcPath, fileName);
            std::error_code se;
            llvm::raw_fd_ostream sos(srcPath, se, llvm::sys::fs::OF_Text);
            if (se) {
              llvm::errs() << "error: cannot open " << srcPath << ": " << se.message() << "\n";
              return failure();
            }
            writeSourcePreamble(sos, headerName);
            for (const SplitMethodDef *m : defs)
              sos << m->definition << "\n";
            writeSourceEpilogue(sos);

            CppManifestSource info;
            info.path = fileName.str();
            info.module = moduleName;
            info.shard = shard.str();
            info.kind = kind.str();
            info.probeOnly = probeOnlyModule;
            auto srcOrErr = llvm::MemoryBuffer::getFile(srcPath);
            if (!srcOrErr) {
              llvm::errs() << "error: cannot read generated source " << srcPath << " for manifest metadata\n";
              return failure();
            }
            llvm::StringRef srcText = (*srcOrErr)->getBuffer();
            info.bytes = static_cast<uint64_t>(srcText.size());
            info.lines = static_cast<uint64_t>(countLines(srcText));
            info.sourceHash = md5HexOfString(srcText);
            info.complexityScore = computeComplexityScore(info.lines, info.bytes, info.kind);
            info.predictedCompileCost = computePredictedCompileCost(info.complexityScore, info.kind);
            cppManifestSources.push_back(std::move(info));
            return success();
          };

          std::vector<const SplitMethodDef *> allMethods;
          std::vector<const SplitMethodDef *> coreMethods;
          std::vector<const SplitMethodDef *> evalMethods;
          std::vector<const SplitMethodDef *> tickMethods;
          std::vector<const SplitMethodDef *> combMethods;
          size_t totalBytes = 0;
          size_t totalLines = 0;
          allMethods.reserve(split->methods.size());
          for (const auto &m : split->methods) {
            const SplitMethodDef *pm = &m;
            allMethods.push_back(pm);
            totalBytes += m.bytes;
            totalLines += m.lines;
            if (m.kind == "comb")
              combMethods.push_back(pm);
            else if (m.kind == "eval")
              evalMethods.push_back(pm);
            else if (m.kind == "tick")
              tickMethods.push_back(pm);
            else
              coreMethods.push_back(pm);
          }

          bool oversized =
              (totalLines > static_cast<size_t>(cppShardThresholdLines)) ||
              (totalBytes > static_cast<size_t>(cppShardThresholdBytes));

          if (!oversized) {
            if (failed(writeSourceFile(moduleName + ".cpp", "module", "000", allMethods)))
              return 1;
          } else {
            bool wroteAny = false;
            if (failed(writeSourceFile(moduleName + "__core.cpp", "core", "core", coreMethods)))
              return 1;
            if (!coreMethods.empty())
              wroteAny = true;
            auto shardPredictedCost = [&](size_t lines, size_t bytes, llvm::StringRef kind) -> double {
              return computePredictedCompileCost(
                  computeComplexityScore(static_cast<uint64_t>(lines), static_cast<uint64_t>(bytes), kind), kind);
            };

            constexpr double kShardSoftMaxSourcePredictedCompileCost =
                kHardMaxSourcePredictedCompileCost * 0.90;

            auto writeMaybeShardedMethods = [&](llvm::StringRef stem,
                                                llvm::StringRef kind,
                                                llvm::ArrayRef<const SplitMethodDef *> defs,
                                                bool allowSharding) -> LogicalResult {
              if (defs.empty())
                return success();

              size_t totalBytesLocal = 0;
              size_t totalLinesLocal = 0;
              for (const SplitMethodDef *m : defs) {
                totalBytesLocal += m->bytes;
                totalLinesLocal += m->lines;
              }
              double totalPredictedCostLocal = shardPredictedCost(totalLinesLocal, totalBytesLocal, kind);
              bool needsSharding =
                  allowSharding && defs.size() > 1 &&
                  ((totalBytesLocal > static_cast<size_t>(cppShardThresholdBytes)) ||
                   (totalLinesLocal > static_cast<size_t>(cppShardThresholdLines)) ||
                   (totalPredictedCostLocal > kShardSoftMaxSourcePredictedCompileCost));

              if (!needsSharding) {
                if (failed(writeSourceFile(moduleName + "__" + stem.str() + ".cpp", kind, stem, defs)))
                  return failure();
                wroteAny = true;
                return success();
              }

              size_t shardIdx = 0;
              std::vector<const SplitMethodDef *> shardDefs;
              size_t shardBytes = 0;
              size_t shardLines = 0;
              auto flushShard = [&]() -> LogicalResult {
                if (shardDefs.empty())
                  return success();
                char shardNum[8];
                std::snprintf(shardNum, sizeof(shardNum), "%03zu", shardIdx++);
                if (failed(writeSourceFile(moduleName + "__" + stem.str() + "_" + shardNum + ".cpp",
                                           kind, shardNum, shardDefs)))
                  return failure();
                wroteAny = true;
                shardDefs.clear();
                shardBytes = 0;
                shardLines = 0;
                return success();
              };

              for (const SplitMethodDef *m : defs) {
                double projectedCost =
                    shardPredictedCost(shardLines + m->lines, shardBytes + m->bytes, kind);
                bool limitHit =
                    !shardDefs.empty() &&
                    ((shardBytes + m->bytes > static_cast<size_t>(cppShardThresholdBytes)) ||
                     (shardLines + m->lines > static_cast<size_t>(cppShardThresholdLines)) ||
                     (projectedCost > kShardSoftMaxSourcePredictedCompileCost));
                if (limitHit) {
                  if (failed(flushShard()))
                    return failure();
                }
                shardDefs.push_back(m);
                shardBytes += m->bytes;
                shardLines += m->lines;
              }
              return flushShard();
            };

            // tick methods can be enormous for large top-level modules (e.g. JanusBccBackendCompat).
            // Allow sharding to avoid compiler instability/timeouts on a single huge TU.
            if (failed(writeMaybeShardedMethods("tick", "tick", tickMethods, /*allowSharding=*/true)))
              return 1;

            if (failed(writeMaybeShardedMethods("eval", "eval", evalMethods, /*allowSharding=*/true)))
              return 1;
            if (failed(writeMaybeShardedMethods("comb", "comb", combMethods, /*allowSharding=*/true)))
              return 1;

            if (!wroteAny) {
              if (failed(writeSourceFile(moduleName + "__core.cpp", "core", "core", allMethods)))
                return 1;
            }
          }
        } else {
          std::error_code fe;
          llvm::raw_fd_ostream hos(headerPath, fe, llvm::sys::fs::OF_Text);
          if (fe) {
            llvm::errs() << "error: cannot open " << headerPath << ": " << fe.message() << "\n";
            return 1;
          }
          hos << "// pyCircuit C++ emission (prototype)\n";
          hos << "#pragma once\n";
          hos << "#include <cstdlib>\n";
          hos << "#include <iostream>\n";
          hos << "#include <memory>\n";
          hos << "#include <cpp/pyc_sim.hpp>\n";
          for (const std::string &dep : deps[f.getSymName()])
            hos << "#include \"" << dep << ".hpp\"\n";
          hos << "\nnamespace pyc::gen {\n\n";
          hos << emitted;
          hos << "\n} // namespace pyc::gen\n";
        }

        cppFiles.push_back(headerName);
      }

      if (splitModule) {
        if (failed(enforceCppCompileBudgets(*module, cppManifestSources)))
          return 1;
        llvm::SmallString<256> manifestPathStorage;
        if (!cppManifestPath.empty()) {
          manifestPathStorage = cppManifestPath;
        } else {
          manifestPathStorage = outDir;
          llvm::sys::path::append(manifestPathStorage, "cpp_compile_manifest.json");
        }
        std::vector<std::string> includeDirs = {std::string(outDir)};
        std::vector<std::string> compileDefines;
        std::string topHeaderName = top + ".hpp";
        llvm::json::Object manifestProfile = buildProfileSummary();
        manifestProfile["pycc_peak_rss_bytes"] = static_cast<int64_t>(getPeakRssBytes());
        manifestProfile["pass_time_ms"] = static_cast<int64_t>(passMs);
        auto toolchainRoot = findToolchainRoot(argv[0]);
        if (failed(writeCppCompileManifest(manifestPathStorage, top, cppManifestSources,
                                           includeDirs, compileDefines, toolchainRoot, topHeaderName,
                                           manifestProfile)))
          return 1;
      }

      if (failed(updateManifest(outDir, top, /*verilogMods=*/std::nullopt, std::move(cppFiles))))
        return 1;

      llvm::SmallString<256> statsPath(outDir);
      llvm::sys::path::append(statsPath, "compile_stats.json");
      if (failed(writeCompileStatsJson(statsPath, compileStats)))
        return 1;
      emitMs = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tEmitStart).count());
      if (failed(writeProfileArtifact("out-dir:cpp")))
        return 1;

      return 0;
    }

    llvm::errs() << "error: unknown --emit kind: " << emitKind << "\n";
    return 1;
  }

  std::error_code ec;
  llvm::raw_fd_ostream os(outputFilename, ec, llvm::sys::fs::OF_Text);
  if (ec) {
    llvm::errs() << "error: cannot open " << outputFilename << ": " << ec.message() << "\n";
    return 1;
  }

  if (emitKind == "verilog") {
    if (cppOnly) {
      llvm::errs() << "error: --emit=verilog is not allowed with --sim-mode=cpp-only\n";
      return 1;
    }
    pyc::VerilogEmitterOptions opts;
    opts.includePrimitives = includePrims;
    if (targetKind == "fpga")
      opts.targetFpga = true;
    else if (targetKind != "default") {
      llvm::errs() << "error: unknown --target: " << targetKind << " (expected: default|fpga)\n";
      return 1;
    }
    if (failed(pyc::emitVerilog(*module, os, opts)))
      return 1;
    if (failed(writeSingleOutputStats()))
      return 1;
    emitMs = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tEmitStart).count());
    if (failed(writeProfileArtifact("single:verilog")))
      return 1;
    return 0;
  }
  if (emitKind == "cpp") {
    pyc::CppEmitterOptions cppEmitOpts;
    if (cppShardMaxAstNodes > 0) {
      cppEmitOpts.evalTopoChunkNodes = cppShardMaxAstNodes;
      cppEmitOpts.combChunkNodes = cppShardMaxAstNodes;
    }
    cppEmitOpts.probePlanPath = probePlanPath;
    if (failed(pyc::emitCpp(*module, os, cppEmitOpts)))
      return 1;
    if (failed(writeSingleOutputStats()))
      return 1;
    emitMs = static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now() - tEmitStart).count());
    if (failed(writeProfileArtifact("single:cpp")))
      return 1;
    return 0;
  }

  llvm::errs() << "error: unknown --emit kind: " << emitKind << "\n";
  return 1;
}
